import LeanFlagAlgebras.Core.Compute.Mask3

-- Generated by scripts/exact_certificate/derive_full_seven_converged_chain.py from certificate/K4_turan_order7_certificate.json;
-- see manifest.json for the certificate hash.
-- 7 rows; entries shifted by 45056477 into the naturals.
namespace FlagAlgebras.Core.Tetrahedron.FullSevenConverged

set_option maxHeartbeats 4000000
set_option maxRecDepth 200000

private def f7s1RawP0 : List ℕ :=
  [46012783, 30839270, 15106423, 1, 88236253, 75379144, 59619800, 46099262, 45243872, 46169422,
   40053945, 39747032, 45957164, 45849752, 44321526, 43290350, 46082242, 45488033, 44822497, 46496084,
   44521575, 47096918, 44572070, 45367690, 45081069, 45364488, 45039344, 44288134, 45032634, 45098388,
   45187502, 45000483, 45127093, 45027096, 45046979, 45053772, 45016057, 45056972, 45048691, 45057881,
   45015052, 45076214, 45056508, 45056484, 45056505, 45056507, 45056479, 45056506, 45056567]

def f7s1Raw : List ℕ :=
  f7s1RawP0

end FlagAlgebras.Core.Tetrahedron.FullSevenConverged
