-- Generated by scripts/exact_certificate/derive_full_seven_converged_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Sweep7_37.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenConverged.TetrahedronOrder7Check

/-! Certificate sweep block 37 of 49: representatives 740–759.

Machine-generated. Every admissible labeled seven-vertex extension of
these representatives is evaluated and compared with the certificate
bound. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenConverged

set_option maxRecDepth 100000

lemma sweepBlock_37 : sweepBlockOf 37 = true := by native_decide

end FlagAlgebras.Core.Tetrahedron.FullSevenConverged
