#!/usr/bin/env python3
"""Generate the FullSevenLong Lean chain for the pinned 794-factor certificate.

The certificate-dependent modules of the chain are instantiated from 105 proof
templates (scripts/exact_certificate/templates/Examples/), written for an
earlier certificate with the same block structure. The generator applies the
structural assembly (full_seven_assembly.extend_template), replaces every
supported factor table, the scale, the stationarity multiplier, the recomputed
class numbers and the bound, redirects the certificate-dependent imports into
the FullSevenLong namespace, writes the three old-family factor-table modules
and the axiom audit, and records every replacement site and every hash in
manifest.json. The thirteen five-root semantic modules are handwritten sources
of the chain; their hashes are recorded, not generated.

This generator is not a verifier: building the generated headlines and
auditing the axioms are required before claiming a Lean proof.
"""
from __future__ import annotations

import argparse
from fractions import Fraction
import json
from pathlib import Path
import re
import sys

from full_seven_long_common import (ACTIVE_ROWS, ACTIVE_TYPES, AUDIT, BOUND_FRACTION, CERT,
                                    CERT_SHA, COLUMN_DENOMINATOR, COLUMN_NUMERATOR,
                                    EXAMPLE_MASK, FIVE_ROOT_MODULES, GENERATED, LEAN_BOUND,
                                    NS, OLD_FAMILY_COUNTS, OLD_FAMILY_DIMS,
                                    OLD_FAMILY_TEMPLATES, PREFIX, ROOT, SCALE, TAU_NUMERATOR,
                                    TEMPLATES, TOTAL_ENTRIES, TOTAL_FACTORS, certificate_bytes,
                                    read_text, sha_text, text_sha, write_lf)

BASE_PREFIX = "LeanFlagAlgebras.Core.Examples."
BASE_NS = "FlagAlgebras.Core.Tetrahedron"
sys.path.insert(0, str(ROOT / "search"))
from analyze_certificate import rebuild_components  # noqa: E402
from exactify_five_root import validate_arithmetic  # noqa: E402
from full_seven_assembly import extend_template  # noqa: E402

# Constants of the templates' certificate, replaced as whole words.
ORIGINAL_LITERALS = {10000000000: SCALE**2, 7200000000000: 720 * SCALE**2,
                     50400000000000: COLUMN_DENOMINATOR, 1219077971869: TAU_NUMERATOR,
                     28208330834196: COLUMN_NUMERATOR}
STALE_LITERALS = [2350694236183, 7605763817, *ORIGINAL_LITERALS]


class Sites:
    """Records every replacement applied to one template."""

    def __init__(self):
        self.log = []

    def exact(self, text, old, new, count=1):
        actual = text.count(old)
        if actual != count:
            raise ValueError(f"Expected {count} occurrences of {old!r}, found {actual}")
        self.log.append({"old": old, "new": new, "count": count})
        return text.replace(old, new)

    def regex(self, text, pattern, repl, label, flags=0, expected=None):
        text, count = re.subn(pattern, repl, text, flags=flags)
        if expected is not None and count != expected:
            raise ValueError(f"Expected {expected} matches of {label}, found {count}")
        if count:
            self.log.append({"site": label, "count": count})
        return text, count

    def optional(self, text, old, new):
        count = text.count(old)
        if count:
            self.log.append({"old": old, "new": new, "count": count})
        return text.replace(old, new)


def list_literal(values, width=10):
    return "[" + ",\n   ".join(", ".join(map(str, values[i:i+width]))
                                  for i in range(0, len(values), width)) + "]"


def replace_list(sites, text, name, value):
    pattern = rf"(\bdef {name} : [^\n]+ :=\s*)\[.*?\](?=\s*(?:/|def |set_option |end |private def ))"
    text, count = re.subn(pattern, lambda m: m[1] + value + "\n\n", text, flags=re.S)
    if count != 1:
        raise ValueError(f"Could not uniquely replace {name}")
    sites.log.append({"site": f"list {name}", "count": 1})
    return text


def factor_module(name, rows, shift, source):
    flat = [int(v) + shift for row in rows for v in row]
    chunks = [flat[i:i+600] for i in range(0, len(flat), 600)]
    lines = ["import LeanFlagAlgebras.Core.Compute.Mask3", "",
             f"-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py from {source};",
             "-- see manifest.json for the certificate hash.",
             f"-- {len(rows)} rows; entries shifted by {shift} into the naturals.",
             f"namespace {NS}", "", "set_option maxHeartbeats 4000000",
             "set_option maxRecDepth 200000", ""]
    for i, chunk in enumerate(chunks):
        lines.extend([f"private def {name}P{i} : List ℕ :=", "  " + list_literal(chunk), ""])
    lines.extend([f"def {name} : List ℕ :=",
                  "  " + (" ++ ".join(f"{name}P{i}" for i in range(len(chunks))) or "[]"),
                  "", f"end {NS}", ""])
    return "\n".join(lines)


AUDITED = ["tetraTuranDensity_le_certValue", "maxDens_eq_exTetra",
           "tendsto_tetraTuranDensity", "edge_le_certBound_of_stationary",
           "columnValue_le_columnBound", "finiteBoost",
           "tetraTuranDensity_le_certValue_finite",
           "turanDensity_le_of_stationary_bound",
           "isDegreeStationary_of_maximizer", "maximizerIsStationary",
           "fiveRootSOS_nonneg", "fiveRootElt_eq_scaled",
           "s5ColumnNum_eq_ordered", "s5ColumnNum_eq_ordered_sum"]


def audit_source():
    lines = [f"import {PREFIX}TetrahedronDifferential",
             f"import {PREFIX}TetrahedronBoost", ""]
    for name in ("tetraTuranDensity_le_certValue", "tetraTuranDensity_le_certValue_finite"):
        lines += [f"example : {NS}.tetraTuranDensity ≤ ({LEAN_BOUND} : ℝ) :=",
                  f"  {NS}.{name}", ""]
    lines += [f"#check {NS}.tetraTuranDensity_le_certValue"]
    lines += [f"#print axioms {NS}.{name}" for name in AUDITED]
    lines += ["#print axioms FlagAlgebras.Core.isStationary_of_maximizer",
              "#print axioms FlagAlgebras.Core.Tetrahedron.gamma56_eq_rooting5040",
              "#print axioms FlagAlgebras.Core.sum_injective_filter_eq_rootSubset_perm", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--certificate", type=Path, default=CERT,
                        help="must be the pinned FullSevenLong certificate (hash-checked)")
    args = parser.parse_args()
    if args.certificate.resolve() != CERT.resolve():
        parser.error("FullSevenLong generation is pinned to " + str(CERT))
    raw = certificate_bytes()
    cert = json.loads(raw)
    _, five = validate_arithmetic(cert)
    if not five or not any(b["factors"] for b in cert["order7_s5_blocks"]):
        raise ValueError("FullSevenLong generation requires active five-root factors")
    original = json.loads((ROOT / "certificate/legacy/K4_turan_order7_symmetry_compressed_certificate.json").read_text())
    for key in ("H_representatives", "order6_blocks", "normalizations"):
        if cert[key] != original[key]:
            raise ValueError(f"The assembly requires the original {key}")
    factors = cert["order6_factors_by_block"] + [cert[k] for k in (
        "order7_s1_factors", "order7_s3_nonedge_factors", "order7_s3_edge_factors")]
    for rows, dim in zip(factors, OLD_FAMILY_DIMS):
        assert all(len(row) == dim and all(type(v) is int for v in row) for row in rows)
    assert list(map(len, factors)) == OLD_FAMILY_COUNTS, list(map(len, factors))
    assert all(not factors[i] for i in (0, 1, 3, 4)), "Additional order-six block proofs are required"
    active = [b for b in cert["order7_s5_blocks"] if b["factors"]]
    assert [b["type_mask"] for b in active] == ACTIVE_TYPES
    assert [len(b["factors"]) for b in active] == ACTIVE_ROWS
    all_rows = [row for rows in factors for row in rows] + [row for b in active for row in b["factors"]]
    assert len(all_rows) == cert["total_integer_square_factors"] == TOTAL_FACTORS
    assert sum(map(len, all_rows)) == TOTAL_ENTRIES
    scale = cert["scale"]
    if scale != SCALE:
        raise ValueError("The five-root scaling bridge requires scale 2,000,000")
    tau = cert["stationarity"]["tau_numerator"]
    assert tau == TAU_NUMERATOR and cert["stationarity"]["tau_denominator"] == scale**2
    denominator = 5040 * scale**2
    numerator = cert["bound_numerator_unreduced"]
    assert numerator == COLUMN_NUMERATOR and denominator == COLUMN_DENOMINATOR
    bound = Fraction(numerator, denominator)
    assert cert["common_denominator_unreduced"] == denominator
    assert Fraction(cert["bound_fraction"]) == bound == BOUND_FRACTION
    assert Fraction(5, 9) < bound < Fraction(1123, 2000)
    assert cert["example_maximizing_raw_mask"] == EXAMPLE_MASK
    gap = Fraction(1123, 2000) - bound
    shift = max(1, 1 + max(abs(v) for rows in factors[9:] for row in rows for v in row))
    source = CERT.relative_to(ROOT).as_posix()

    modules = {p.stem: read_text(p) for p in TEMPLATES.glob("*.lean")}
    closure = set(OLD_FAMILY_TEMPLATES)
    assert len(closure) == 105 and closure == set(modules), "template set changed"
    blocks, edge, squares, stat = rebuild_components(cert)
    class_numbers = [int(v) for v in edge + squares + stat]
    assert len(class_numbers) == 964
    for block, metadata in zip(blocks, cert["order6_blocks"]):
        assert block.flags == metadata["flags"] and block.denominator == metadata["denominator"]

    outputs = {}
    changes = {}
    for name in sorted(closure):
        sites = Sites()
        text = extend_template(name, modules[name])
        if name == "TetrahedronOrder7Extension":
            text = sites.exact(text, f"import {BASE_PREFIX}TetrahedronOrder7Pairwise\n",
                               f"import {BASE_PREFIX}TetrahedronOrder7Data\nimport {BASE_PREFIX}TetrahedronMask\n")
        if name == "TetrahedronOrder7ClassNum":
            text = f"import {BASE_PREFIX}TetrahedronOrder7Pairwise\n" + text
            sites.log.append({"site": "prepend import Pairwise", "count": 1})
        if name in {"TetrahedronOrder7Realize", "TetrahedronOrder7Verified"}:
            text = f"import {BASE_PREFIX}TetrahedronOrder7Distinct\n" + text
            sites.log.append({"site": "prepend import Distinct", "count": 1})
        if name == "TetrahedronOrder7BlockCheck":
            text = sites.exact(text, f"import {BASE_PREFIX}TetrahedronOrder7ClassNum\n", "")
        if name == "TetrahedronOrder7Blocks":
            for field, index in [("facs24L", 2), ("facs45_0L", 5), ("facs45_1L", 6),
                                 ("facs45_3L", 7), ("facs45_7L", 8)]:
                rows = factors[index]
                literal = "[" + ",\n   ".join(list_literal(row) for row in rows) + "]"
                text = replace_list(sites, text, field, literal)
            text = replace_list(sites, text, "classNumsRef", list_literal(class_numbers, 6))
        if name == "TetrahedronOrder7Column":
            text = f"import {PREFIX}TetrahedronOrder7FiveRootColumn\n" + text
            sites.log.append({"site": "prepend import FiveRootColumn", "count": 1})
            text = sites.exact(text,
                "  deckValue m + 36 * s1Value m + 4 * s3Value m",
                "  deckValue m + 36 * s1Value m + 4 * s3Value m + s5ColumnNum m")
            text = f"import {BASE_PREFIX}TetrahedronOrder7Checker\n" + text
            sites.log.append({"site": "prepend import Checker", "count": 1})
            begin = text.index("private def f7s1RawP0 : List ℕ :=")
            end = text.index("def gram7s1 : Array ℤ :=", begin)
            text = text[:begin] + "-- Factor tables are imported from the three generated data modules.\n\n" + text[end:]
            sites.log.append({"site": "remove inline factor tables", "count": 1})
            for tag, old, count, dim in [("s1", 6, len(factors[9]), 7), ("s30", 60, len(factors[10]), 236),
                                         ("s31", 46, len(factors[11]), 191)]:
                text = sites.exact(text, f"gramFromFlat {dim} {old} (unshift f7{tag}Raw)",
                                   f"gramFromFlat {dim} {count} (unshift f7{tag}Raw)")
            text = sites.exact(text, "def factorShift : ℤ := 4000000", f"def factorShift : ℤ := {shift}")
            text = sites.exact(text, "def exampleColumn : ℕ := 14657251566",
                               f"def exampleColumn : ℕ := {cert['example_maximizing_raw_mask']}")
            text = sites.exact(text, "import " + BASE_PREFIX + "TetrahedronOrder7Blocks\n",
                               "import " + BASE_PREFIX + "TetrahedronOrder7Blocks\n" +
                               "".join(f"import {PREFIX}TetrahedronOrder7Factors{tag}\n" for tag in ("S1", "S30", "S31")))
        # Only these sites are factor-row ranges; other six-element ranges are
        # combinatorial split counts and must remain six.
        if name in {"TetrahedronOrder7RootFlags", "TetrahedronOrder7CellWeight",
                    "TetrahedronOrder7RootMatch", "TetrahedronOrder7RootScaled", "TetrahedronOrder7RootSOS"}:
            text, _ = sites.regex(text, r"\b((?:List|Finset)\.range) (60|46)\b",
                lambda m: f"{m[1]} {len(factors[10 if m[2] == '60' else 11])}", "range 60|46 -> row count")
            for tag, old, index in (("S30", 60, 10), ("S31", 46, 11), ("S1", 6, 9)):
                text = sites.optional(text, f"(fun r => f{tag} r i * f{tag} r j) {old}]",
                                      f"(fun r => f{tag} r i * f{tag} r j) {len(factors[index])}]")
            text = sites.optional(text, "(hpart 60 false", f"(hpart {len(factors[10])} false")
            text = sites.optional(text, "(hpart 46 true", f"(hpart {len(factors[11])} true")
            if name == "TetrahedronOrder7RootMatch":
                text = sites.exact(text, "∑ r ∈ Finset.range 6,", f"∑ r ∈ Finset.range {len(factors[9])},")
            else:
                text, _ = sites.regex(text, r"\b((?:List|Finset)\.range) 6\b",
                                      lambda m: f"{m[1]} {len(factors[9])}", "range 6 -> one-root row count")
        # Replace whole constants, never substrings inside packed lookup tables
        # or resource limits (which happen to contain some of the same numerals).
        for literal, value in ORIGINAL_LITERALS.items():
            text, _ = sites.regex(text, rf"\b{literal}\b", str(value), f"{literal} -> {value}")
        text = sites.optional(text, "certScale : ℤ := 100000", f"certScale : ℤ := {scale}")
        text = sites.optional(text, "certScale = (100000 : ℤ)", f"certScale = ({scale} : ℤ)")
        for old, value in [("2350694236183", bound), ("7605763817", gap)]:
            text, _ = sites.regex(text, old + r"\s*/\s*4200000000000",
                                  f"{value.numerator} / {value.denominator}", f"{old}/4200000000000 -> fraction")
        text = sites.optional(text, "0.5596891", f"{float(bound):.10f}")
        text = sites.optional(text, "0.0018108", f"{float(gap):.10f}")
        for mod in closure:
            text = sites.optional(text, f"import {BASE_PREFIX}{mod}\n", f"import {PREFIX}{mod}\n")
        text = sites.exact(text, f"namespace {BASE_NS}\n", f"namespace {NS}\n")
        text = sites.exact(text, f"end {BASE_NS}\n", f"end {NS}\n")
        for literal in STALE_LITERALS:
            if re.search(rf"\b{literal}\b", text):
                raise ValueError(f"Stale constant {literal} survives in {name}")
        template_path = (TEMPLATES / (name + ".lean")).relative_to(ROOT).as_posix()
        header = (f"-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.\n"
                  f"-- The certificate and all source hashes are recorded in this directory's manifest.json.\n"
                  f"-- Proof template: {template_path}; certificate-dependent imports redirected.\n")
        outputs[name + ".lean"] = header + text
        changes[name] = {"template": template_path,
                         "template_sha256": sha_text(modules[name]), "replacements": sites.log}

    # The handwritten five-root semantic modules are sources of the chain, not
    # generated: record their hashes so the manifest describes the whole directory.
    handwritten = {}
    for name in FIVE_ROOT_MODULES:
        path = GENERATED / (name + ".lean")
        if not path.exists():
            raise FileNotFoundError(f"handwritten module missing: {path}")
        handwritten[name + ".lean"] = text_sha(path)

    for tag, key, rows in zip(("S1", "S30", "S31"), ("f7s1Raw", "f7s30Raw", "f7s31Raw"), factors[9:]):
        outputs[f"TetrahedronOrder7Factors{tag}.lean"] = factor_module(key, rows, shift, source)
    audit = audit_source()

    GENERATED.mkdir(parents=True, exist_ok=True)
    for filename, text in outputs.items():
        write_lf(GENERATED / filename, text)
    write_lf(GENERATED / ".gitattributes", "# Generated LF sources; hashes in manifest.json are of LF text.\n* text eol=lf\n")
    write_lf(AUDIT, audit)
    manifest = {
        "chain": NS, "certificate": source, "certificate_sha256": CERT_SHA, "bound": str(bound),
        "hash_convention": "certificate: raw bytes; Lean, Python and JSON sources: UTF-8 text with CRLF normalized to LF",
        "scale": scale, "column_numerator": numerator, "column_denominator": denominator,
        "stationarity_tau_numerator": tau, "example_maximizing_raw_mask": cert["example_maximizing_raw_mask"],
        "gap_below_published": str(gap),
        "factor_counts": list(map(len, factors)),
        "five_root_factor_counts": {str(b["type_mask"]): len(b["factors"]) for b in cert["order7_s5_blocks"]},
        "total_integer_square_factors": len(all_rows), "total_integer_entries": sum(map(len, all_rows)),
        "factor_shift": shift, "class_number_count": len(class_numbers),
        "templates": changes, "handwritten_modules": handwritten,
        "generated_sha256": {k: sha_text(v) for k, v in outputs.items()},
        "generator_sha256": text_sha(Path(__file__)),
        "assembly_transform_sha256": text_sha(Path(__file__).with_name("full_seven_assembly.py")),
        "common_sha256": text_sha(Path(__file__).with_name("full_seven_long_common.py")),
        "axiom_audit": AUDIT.relative_to(ROOT).as_posix(),
        "axiom_audit_sha256": sha_text(audit),
    }
    write_lf(GENERATED / "manifest.json", json.dumps(manifest, indent=2) + "\n")
    for filename, digest in manifest["generated_sha256"].items():
        assert text_sha(GENERATED / filename) == digest, filename
    print(f"Generated {len(outputs)} modules in {GENERATED}; bound {bound}. "
          "Build and axiom audit still required.")


if __name__ == "__main__":
    main()
