-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronDifferential.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Differential.Stationary
import LeanFlagAlgebras.Core.Differential.Upward
import LeanFlagAlgebras.Core.Limit.Sampling
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronDegreeExpand
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronTuran
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronAntitone
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronExtremal

/-! # The differential method at the tetrahedron, and the headline bound

This module states the headline theorems of the development:
`tetraTuranDensity_le_certValue` (the Turán density of the tetrahedron is at
most the certificate value) and `tetraTuranDensity_lt_published`. Their only
input from the finite layer is the antitonicity of the maximal densities
(`maxDensAntitone`); the degree-stationarity of the maximizer comes from
Razborov's Corollary 4.6(a), not from the finite cloning boost of
`TetrahedronBoost`, which is kept alongside as an independent route
(`tetraTuranDensity_le_certValue_finite`).

The generic differential method of `Core/Differential` (Razborov's
Theorem 4.3 and its consequence `isStationary_of_maximizer`), instantiated
at the tetrahedron-free theory:

* the theory is vertex uniform, with the single labeled vertex as its
  vertex type (`instVertexUniform`);
* the hyperedge has a single rooting, the degree flag
  (`labelPlacements_edge`, `muVec_edge`);
* every positive homomorphism has edge density at most the finite Turán
  density (`positiveHom_edge_le_turanDensity`), so the homomorphism realized
  by a sequence of exact maximizers is a maximizer;

hence that homomorphism is degree-stationary, the certified bound applies
to it, and the finite Turán density obeys the certificate bound
(`turanDensity_le_certBound_differential`) — the classical route through
Corollary 4.6(a), with no finite surrogate. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core Filter
open Classical

/-! ## Vertex uniformity -/

/-- The tetrahedron-free theory is vertex uniform: every vertex of every
member is a copy of the single labeled vertex, since hyperedges have
injective support and a one-vertex model carries none. -/
instance instVertexUniform : TetraFree.VertexUniform vertexGraph.toModel where
  interp_const := by
    intro V N hN v r f
    have hinj : N.SupportInj r := (hN.1 r).2
    constructor
    · intro h
      exfalso
      have h01 : (⇑(constEmb v) ∘ f) 0 = (⇑(constEmb v) ∘ f) 1 := rfl
      exact absurd (hinj _ h h01) (by cases r; decide)
    · intro h
      exfalso
      have hf : Function.Injective f := h.1
      exact absurd (hf (Subsingleton.elim (f 0) (f 1))) (by cases r; decide)

/-! ## The rootings of the hyperedge -/

/-- The degree flag, sized. -/
noncomputable def degreeFin : FinFlag TetraFree vertexGraph.toModel :=
  ⟨3, degreeSym3Flag.toFlag (𝕋 := TetraFree) degreeSym3Flag_wf degreeSym3Flag_mem⟩

lemma degreeFlag_eq_basis : degreeFlag = ⟦basisVector degreeFin⟧ :=
  rfl

/-- The labeled hyperedge. -/
def edgeLabeled : LabeledFlag TetraFree emptyType (Fin 3) :=
  LabeledFlag.ofEmptyType edgeGraph_mem

lemma edgeFin_snd : edgeFin.2 = edgeLabeled.toFlag :=
  rfl

/-- The labeled degree flag is the hyperedge rooted at `0`. -/
lemma degreeLabeled_eq_rootedAt :
    degreeSym3Flag.toLabeledFlag (𝕋 := TetraFree) degreeSym3Flag_wf degreeSym3Flag_mem
      = rootedAt vertexGraph.toModel edgeLabeled 0 :=
  LabeledFlag.ext_of rfl (Function.Embedding.ext fun t => by
    show (![0] : Fin 1 → Fin 3) t = 0
    rw [Subsingleton.elim t 0]
    rfl)

/-- Any rooting of the hyperedge is the rooting at `0`: the hyperedge is
vertex transitive. -/
noncomputable def rootedEdge_iso (w : Fin 3) :
    rootedAt vertexGraph.toModel edgeLabeled w
      ≃ᶠ rootedAt vertexGraph.toModel edgeLabeled 0 where
  toIso := Sym3Graph.modelIsoOfPerm (Equiv.swap w 0) (by revert w; decide)
  root_preserve := fun _ => Equiv.swap_apply_left w 0

/-- Rooting respects isomorphism of the unlabeled hosts. -/
noncomputable def rootedAt_congr {S : Signature} [S.NullaryFree] {𝕋 : RelTheory S}
    {σ₁ : Model S (Fin 1)} [𝕋.VertexUniform σ₁] {V W : Type}
    {N : LabeledFlag 𝕋 (FlagAlgebras.Core.emptyType S) V}
    {N' : LabeledFlag 𝕋 (FlagAlgebras.Core.emptyType S) W} (e : N ≃ᶠ N') (v : V) :
    rootedAt σ₁ N v ≃ᶠ rootedAt σ₁ N' (e.toIso.toEquiv v) where
  toIso := e.toIso
  root_preserve := fun _ => rfl

/-- **The hyperedge has a single rooting**: the degree flag. -/
theorem labelPlacements_edge :
    labelPlacements vertexGraph.toModel edgeFin.2 = {degreeFin.2} := by
  ext F
  rw [mem_labelPlacements, Finset.mem_singleton]
  constructor
  · intro hF
    obtain ⟨G, rfl⟩ := Quotient.exists_rep F
    change (G.toFlag).unlabel = edgeLabeled.toFlag at hF
    rw [Flag.unlabel_mk] at hF
    obtain ⟨e⟩ := Quotient.exact hF
    have iso : rootedAt vertexGraph.toModel G.unlabel (G.rootEmbed.toEmbedding 0)
        ≃ᶠ rootedAt vertexGraph.toModel edgeLabeled 0 :=
      (rootedAt_congr e _).trans (rootedEdge_iso _)
    rw [rootedAt_unlabel_root, ← degreeLabeled_eq_rootedAt] at iso
    exact Quotient.sound ⟨iso⟩
  · intro hF
    rw [hF]
    show (degreeSym3Flag.toLabeledFlag (𝕋 := TetraFree) degreeSym3Flag_wf
      degreeSym3Flag_mem).toFlag.unlabel = edgeLabeled.toFlag
    rw [Flag.unlabel_mk]
    exact congrArg LabeledFlag.toFlag
      (LabeledFlag.ext_of rfl (Function.Embedding.ext fun x => x.elim0))

/-- `π̃¹(ρ) = d`: the rootings of the hyperedge sum to the degree flag. -/
theorem muVec_edge : muVec vertexGraph.toModel edgeFin = basisVector degreeFin := by
  unfold muVec
  rw [labelPlacements_edge, Finset.sum_singleton]
  rfl

/-! ## Every homomorphism is below the finite Turán density -/

/-- The edge density of a positive homomorphism is at most the maximal
edge density at any size `n ≥ 3`: expand the hyperedge at size `n`. -/
theorem positiveHom_edge_le_maxDens (φ : PositiveHom TetraFree emptyType) (n : ℕ)
    (hn : 3 ≤ n) : φ edgeElt ≤ maxDens n := by
  rw [edgeElt_eq_basis, basisVector_quot_eq_sum edgeFin n hn, PositiveHom.map_sum]
  simp_rw [PositiveHom.map_smul]
  calc ∑ G : FlagWithSize TetraFree emptyType n,
        (subflagDensity edgeFin.2 G : ℝ) * φ ⟦basisVector ⟨n, G⟩⟧
      ≤ ∑ G : FlagWithSize TetraFree emptyType n, maxDens n * φ ⟦basisVector ⟨n, G⟩⟧ :=
        Finset.sum_le_sum fun G _ =>
          mul_le_mul_of_nonneg_right (le_maxDens G) (positiveHom_basisVector_nonneg φ _)
    _ = maxDens n * ∑ G : FlagWithSize TetraFree emptyType n, φ ⟦basisVector ⟨n, G⟩⟧ := by
        rw [Finset.mul_sum]
    _ = maxDens n := by
        rw [sum_positiveHom_basisVector_eq_one φ n (by simp), mul_one]

/-- **Every positive homomorphism is below the finite Turán density.** -/
theorem positiveHom_edge_le_turanDensity (φ : PositiveHom TetraFree emptyType) :
    φ edgeElt ≤ turanDensity :=
  le_ciInf fun n => positiveHom_edge_le_maxDens φ (n + 3) (by omega)

/-! ## The bound through the differential method -/

/-- The chain's realization predicate is the generic one. -/
theorem realizedBy_iff (φ : PositiveHom TetraFree emptyType)
    (Gs : ℕ → FinFlag TetraFree emptyType) :
    RealizedBy φ Gs ↔ FlagAlgebras.Core.RealizedBy φ Gs :=
  Iff.rfl

/-- **A realized edge maximizer is degree-stationary** (the paper's
Corollary "maximizers are degree-stationary", through Razborov's
Theorem 4.3). -/
theorem isDegreeStationary_of_maximizer (φ : PositiveHom TetraFree emptyType)
    (Gs : ℕ → FinFlag TetraFree emptyType) (h : RealizedBy φ Gs)
    (hmax : IsEdgeMaximizer φ) : IsDegreeStationary φ := by
  have hmax' : ∀ ψ : PositiveHom TetraFree emptyType,
      ψ ⟦basisVector edgeFin⟧ ≤ φ ⟦basisVector edgeFin⟧ := fun ψ => hmax ψ
  rw [IsDegreeStationary, degreeFlag_eq_basis]
  exact isStationary_of_maximizer (σ₁ := vertexGraph.toModel) φ Gs
    ((realizedBy_iff φ Gs).mp h) edgeFin (by decide) hmax' degreeFin muVec_edge

/-- **A realized edge maximizer attaining the finite Turán density exists**,
given the antitone statement: realize a sequence of exact maximizers. -/
theorem exists_realized_maximizer (hmono : MaxDensAntitone) :
    ∃ (ψ : PositiveHom TetraFree emptyType) (Gs : ℕ → FinFlag TetraFree emptyType),
      RealizedBy ψ Gs ∧ IsEdgeMaximizer ψ ∧ ψ edgeElt = turanDensity := by
  have hanti : Antitone fun n : ℕ => maxDens (n + 3) :=
    antitone_nat_of_succ_le fun n => hmono n
  have htend : Tendsto (fun n : ℕ => maxDens (n + 3)) atTop (nhds turanDensity) :=
    tendsto_atTop_ciInf hanti bddBelow_maxDens
  choose Gmax hGmax using fun n => exists_maxDens (n + 3)
  set Gs : ℕ → FinFlag TetraFree emptyType := fun n => ⟨n + 3, Gmax n⟩ with hGs
  have hsz : Tendsto (fun k => (Gs k).1) atTop atTop := by
    have h : (fun k => (Gs k).1) = fun k => k + 3 := rfl
    rw [h]
    exact tendsto_add_atTop_nat 3
  obtain ⟨s, hsmono, ψ, hψ⟩ := exists_realized_subseq Gs hsz
  have hedge : Tendsto (fun k => edgeDens (Gs (s k))) atTop (nhds turanDensity) := by
    have h1 : ∀ k, edgeDens (Gs (s k)) = maxDens (s k + 3) := fun k => hGmax (s k)
    exact Tendsto.congr (fun k => (h1 k).symm) (htend.comp hsmono.tendsto_atTop)
  have hψedge : ψ edgeElt = turanDensity := by
    have h2 := hψ.2 edgeFin
    rw [← edgeElt_eq_basis] at h2
    exact tendsto_nhds_unique h2 hedge
  refine ⟨ψ, fun k => Gs (s k), hψ, fun φ => ?_, hψedge⟩
  rw [hψedge]
  exact positiveHom_edge_le_turanDensity φ

/-- **The consumption theorem of the differential route**: any bound
valid for degree-stationary homomorphisms bounds the finite Turán density.
Only the antitone statement is used from the finite layer. -/
theorem turanDensity_le_of_stationary_bound (hmono : MaxDensAntitone) (B : ℝ)
    (hB : ∀ φ : PositiveHom TetraFree emptyType, IsDegreeStationary φ → φ edgeElt ≤ B) :
    turanDensity ≤ B := by
  obtain ⟨ψ, Gs, hψ, hmax, hψedge⟩ := exists_realized_maximizer hmono
  rw [← hψedge]
  exact hB ψ (isDegreeStationary_of_maximizer ψ Gs hψ hmax)

/-- **The finite Turán density obeys the certified bound**, through the
differential method: the homomorphism realized by a sequence of exact
maximizers is an edge maximizer, hence degree-stationary, hence below the
certificate. Only the antitone statement is used from the finite layer. -/
theorem turanDensity_le_certBound_differential (hmono : MaxDensAntitone) :
    turanDensity ≤ ((certBound : ℚ) : ℝ) :=
  turanDensity_le_of_stationary_bound hmono _ edge_le_certBound_of_stationary

/-- **The unconditional bound, through the differential method.** -/
theorem turanDensity_le_certBound_proved :
    turanDensity ≤ ((certBound : ℚ) : ℝ) :=
  turanDensity_le_certBound_differential maxDensAntitone

/-- **The headline**: the Turán density of the tetrahedron is at most the
certificate value `312372062889819 / 560000000000000 = 0.5578072552…`, one inequality
between an elementary limit and an explicit rational, proved through the
differential method. -/
theorem tetraTuranDensity_le_certValue :
    tetraTuranDensity ≤ 312372062889819 / 560000000000000 := by
  rw [tetraTuranDensity_eq]
  exact turanDensity_le_certBound_proved.trans_eq certBound_cast

/-- The bound, numerically: below the published record `1123/2000`. -/
theorem turanDensity_lt_published : turanDensity < (1123 / 2000 : ℝ) := by
  refine lt_of_le_of_lt turanDensity_le_certBound_proved ?_
  rw [certBound_cast]
  norm_num

/-- The comparison form of the headline: strictly below the previously
published record `1123/2000 = 0.5615`. -/
theorem tetraTuranDensity_lt_published : tetraTuranDensity < 1123 / 2000 := by
  rw [tetraTuranDensity_eq]
  exact turanDensity_lt_published

/-- Eventually below the published record, in elementary terms. -/
theorem eventually_exTetra_lt_published :
    ∀ᶠ n in atTop, (exTetra n : ℝ) / (n.choose 3 : ℝ) < 1123 / 2000 :=
  exTetra_tendsto.eventually_lt_const turanDensity_lt_published

/-! ## The vertex derivative of the edge density (the paper's (Dgrad)) -/

/-- `∂₁ρ = 3 (π¹ρ − d)` on the algebra: the hyperedge has three vertices and
the degree flag as its single rooting. -/
theorem partialVertex_edgeElt :
    partialVertex (σ₁ := vertexGraph.toModel) edgeElt
      = (3 : ℝ) • (upward (σ₁ := vertexGraph.toModel) edgeElt - degreeFlag) := by
  rw [edgeElt_eq_basis, partialVertex_basis, degreeFlag_eq_basis, muElt, muVec_edge]
  show ((3 : ℕ) : ℝ) • _ = (3 : ℝ) • _
  norm_num

/-- **(Dgrad)**: `⟦d · ∂₁ρ⟧₁ = 3 D` — the stationarity element is, up to the
factor `3`, the vertex derivative of the edge density tested against the
degree flag (Theorem 2.8(a) and `⟦d⟧₁ = ρ`). -/
theorem downward_degreeFlag_mul_partialVertex_edgeElt :
    downward (degreeFlag * partialVertex (σ₁ := vertexGraph.toModel) edgeElt)
      = (3 : ℝ) • degreeStationarity := by
  rw [partialVertex_edgeElt, mul_smul_comm, downward_smul, mul_sub, downward_sub,
    mul_comm degreeFlag (upward edgeElt), downward_upward_mul, downward_degreeFlag,
    degreeStationarity_eq]

/-! ## The chain's named statements are theorems -/

/-- **Every positive homomorphism of the tetrahedron-free theory is
realized** (the chain's named statement D2): Razborov's Theorem 3.3,
sampling direction. -/
theorem everyHomRealized : EveryHomRealized := fun φ => by
  obtain ⟨Gs, h⟩ := FlagAlgebras.Core.exists_realizedBy φ
  exact ⟨Gs, (realizedBy_iff φ Gs).mpr h⟩

/-- **An edge-density maximizer is degree-stationary** (the chain's named
statement M2d), through the differential method, with no realization
hypothesis: every homomorphism is realized. -/
theorem maximizerIsStationary : MaximizerIsStationary := fun φ hmax => by
  obtain ⟨Gs, hGs⟩ := everyHomRealized φ
  exact isDegreeStationary_of_maximizer φ Gs hGs hmax

/-- **Every positive homomorphism is below the certificate**, through the
chain's consumption of M2d. -/
theorem edge_le_certBound_all (ψ : PositiveHom TetraFree emptyType) :
    ψ edgeElt ≤ ((certBound : ℚ) : ℝ) := by
  obtain ⟨φmax, _, _, hmax, _⟩ := exists_realized_maximizer maxDensAntitone
  exact edge_le_certBound_forall maximizerIsStationary φmax hmax ψ

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
