-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronBoost.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronStatComb
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronAntitone
import LeanFlagAlgebras.Core.Examples.TetrahedronClone
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronExtremal

/-! # The clone boost, and the unconditional Turán bound

`FiniteBoost` is a theorem. A genuinely negative stationarity
combination is, by `statComb_toFlag_eq`, an exact statement about the
pattern counts `P₀` and `P₁`; if additionally every pair of degrees were
within `n - 2` of each other, the double-count identities would force
the combination above `-258/n` — so for `n` large some degree gap
exceeds `n - 2`, which is more than any codegree, and cloning the
large-degree vertex over the small one strictly gains edges at the same
size while staying tetrahedron-free.

With `MaxDensAntitone` and `FiniteBoost` both proved, the consumption
theorem fires: the finite Turán density of the tetrahedron obeys the
order-7 certificate bound, below the published record
(`turanDensity_le_certBound_finite`, `tetraTuranDensity_le_certValue_finite`).

This is the finite route to the bound, kept alongside the main chain as an
independent check. The headline theorems `tetraTuranDensity_le_certValue`
and `tetraTuranDensity_lt_published` of `TetrahedronDifferential` obtain the
maximizer's degree-stationarity from Razborov's differential method
(Corollary 4.6(a)) instead, and do not depend on this module. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-! ## The normalizer comparison

Nine times the disjoint-pair normalizer is `n - 5` times the `P₁`
normalizer — both are multiples of `C(n,6)`. -/

lemma nine_pairChoose {n : ℕ} (hn : 6 ≤ n) :
    9 * pairChoose n 3 3 = (n - 5) * (30 * n.choose 5) := by
  have h1 : n.choose 6 * Nat.choose 6 3
      = n.choose 3 * (n - 3).choose 3 :=
    choose_mul_choose (by norm_num) hn
  have h2 : n.choose 6 * 6 = n.choose 5 * (n - 5) := by
    simpa using Nat.choose_succ_right_eq n 5
  have h3 : pairChoose n 3 3 = n.choose 3 * (n - 3).choose 3 := rfl
  calc 9 * pairChoose n 3 3
      = 9 * (n.choose 3 * (n - 3).choose 3) := by rw [h3]
    _ = 9 * (n.choose 6 * Nat.choose 6 3) := by rw [h1]
    _ = 30 * (n.choose 6 * 6) := by
        rw [show Nat.choose 6 3 = 20 from rfl]
        ring
    _ = 30 * (n.choose 5 * (n - 5)) := by rw [h2]
    _ = (n - 5) * (30 * n.choose 5) := by ring

/-! ## Crude size bounds

The descending factorials at three and five unfold definitionally, and
`2(n - k) ≥ n` per factor turns them into clean power bounds. All
thresholds are absorbed into `64 ≤ n`. -/

private lemma descFactorial_three (m : ℕ) :
    m.descFactorial 3 = (m - 2) * ((m - 1) * (m * 1)) := rfl

private lemma descFactorial_five (m : ℕ) :
    m.descFactorial 5
      = (m - 4) * ((m - 3) * ((m - 2) * ((m - 1) * (m * 1)))) := rfl

private lemma choose3_mul (m : ℕ) :
    6 * m.choose 3 = (m - 2) * ((m - 1) * (m * 1)) := by
  rw [← descFactorial_three, Nat.descFactorial_eq_factorial_mul_choose,
    show Nat.factorial 3 = 6 from rfl]

private lemma choose5_mul (m : ℕ) :
    120 * m.choose 5
      = (m - 4) * ((m - 3) * ((m - 2) * ((m - 1) * (m * 1)))) := by
  rw [← descFactorial_five, Nat.descFactorial_eq_factorial_mul_choose,
    show Nat.factorial 5 = 120 from rfl]

private lemma edges_card_le {n : ℕ} (G : Sym3Graph n) :
    G.edges.card ≤ n.choose 3 := by
  have hsub : G.edges ⊆ Finset.univ.powersetCard 3 := fun e he =>
    Finset.mem_powersetCard.mpr ⟨Finset.subset_univ _, G.edges_valid e he⟩
  calc G.edges.card ≤ _ := Finset.card_le_card hsub
    _ = n.choose 3 := by
        rw [Finset.card_powersetCard, Finset.card_univ, Fintype.card_fin]

/-- `C(n,3) ≤ 8·C(n-3,3)`: each factor at most doubles. -/
private lemma choose3_ratio {n : ℕ} (hn : 10 ≤ n) :
    n.choose 3 ≤ 8 * (n - 3).choose 3 := by
  have hstep : (n - 2) * ((n - 1) * (n * 1))
      ≤ (2 * (n - 3 - 2)) * ((2 * (n - 3 - 1)) * ((2 * ((n - 3) * 1)))) :=
    Nat.mul_le_mul (by omega)
      (Nat.mul_le_mul (by omega) (by omega))
  have h6 : 6 * n.choose 3 ≤ 8 * (6 * (n - 3).choose 3) := by
    rw [choose3_mul, choose3_mul]
    calc (n - 2) * ((n - 1) * (n * 1))
        ≤ (2 * (n - 3 - 2)) * ((2 * (n - 3 - 1)) * ((2 * ((n - 3) * 1)))) :=
          hstep
      _ = 8 * ((n - 3 - 2) * ((n - 3 - 1) * ((n - 3) * 1))) := by ring
  omega

/-- `n⁴ ≤ C(n,3)·C(n-3,3)` for `n ≥ 64`. -/
private lemma pairChoose_lower {n : ℕ} (hn : 64 ≤ n) :
    n ^ 4 ≤ pairChoose n 3 3 := by
  have hA : n ^ 3 ≤ 24 * n.choose 3 := by
    have hstep : n * (n * (n * 1))
        ≤ (2 * (n - 2)) * ((2 * (n - 1)) * (n * 1)) :=
      Nat.mul_le_mul (by omega) (Nat.mul_le_mul (by omega) le_rfl)
    calc n ^ 3 = n * (n * (n * 1)) := by ring
      _ ≤ (2 * (n - 2)) * ((2 * (n - 1)) * (n * 1)) := hstep
      _ = 4 * ((n - 2) * ((n - 1) * (n * 1))) := by ring
      _ = 4 * (6 * n.choose 3) := by rw [choose3_mul]
      _ = 24 * n.choose 3 := by ring
  have hB : n ^ 3 ≤ 48 * (n - 3).choose 3 := by
    have hstep : n * (n * (n * 1))
        ≤ (2 * (n - 3 - 2)) * ((2 * (n - 3 - 1)) * ((2 * ((n - 3) * 1)))) :=
      Nat.mul_le_mul (by omega) (Nat.mul_le_mul (by omega) (by omega))
    calc n ^ 3 = n * (n * (n * 1)) := by ring
      _ ≤ (2 * (n - 3 - 2)) * ((2 * (n - 3 - 1)) * ((2 * ((n - 3) * 1)))) :=
        hstep
      _ = 8 * ((n - 3 - 2) * ((n - 3 - 1) * ((n - 3) * 1))) := by ring
      _ = 8 * (6 * (n - 3).choose 3) := by rw [choose3_mul]
      _ = 48 * (n - 3).choose 3 := by ring
  have h6 : n ^ 6 ≤ 1152 * pairChoose n 3 3 := by
    calc n ^ 6 = n ^ 3 * n ^ 3 := by ring
      _ ≤ (24 * n.choose 3) * (48 * (n - 3).choose 3) :=
          Nat.mul_le_mul hA hB
      _ = 1152 * (n.choose 3 * (n - 3).choose 3) := by ring
      _ = 1152 * pairChoose n 3 3 := rfl
  have hn2 : 1152 * n ^ 4 ≤ n ^ 6 := by
    calc 1152 * n ^ 4 ≤ (n * n) * n ^ 4 := by
          refine Nat.mul_le_mul ?_ le_rfl
          calc 1152 ≤ 64 * 64 := by norm_num
            _ ≤ n * n := Nat.mul_le_mul hn hn
      _ = n ^ 6 := by ring
  have := le_trans hn2 h6
  omega

/-- `n⁴ ≤ 30·C(n,5)` for `n ≥ 64`. -/
private lemma choose5_lower {n : ℕ} (hn : 64 ≤ n) :
    n ^ 4 ≤ 30 * n.choose 5 := by
  have h5 : n ^ 5 ≤ 16 * (120 * n.choose 5) := by
    have hstep : n * (n * (n * (n * (n * 1))))
        ≤ (2 * (n - 4)) * ((2 * (n - 3)) * ((2 * (n - 2)) *
            ((2 * (n - 1)) * (n * 1)))) :=
      Nat.mul_le_mul (by omega) (Nat.mul_le_mul (by omega)
        (Nat.mul_le_mul (by omega) (Nat.mul_le_mul (by omega) le_rfl)))
    calc n ^ 5 = n * (n * (n * (n * (n * 1)))) := by ring
      _ ≤ (2 * (n - 4)) * ((2 * (n - 3)) * ((2 * (n - 2)) *
            ((2 * (n - 1)) * (n * 1)))) := hstep
      _ = 16 * ((n - 4) * ((n - 3) * ((n - 2) * ((n - 1) * (n * 1))))) := by
          ring
      _ = 16 * (120 * n.choose 5) := by rw [choose5_mul]
  have h64 : 64 * n ^ 4 ≤ n ^ 5 := by
    calc 64 * n ^ 4 ≤ n * n ^ 4 := Nat.mul_le_mul hn le_rfl
      _ = n ^ 5 := by ring
  have := le_trans h64 h5
  omega

/-! ## The spread bound

If every two degrees differ by at most `n - 2`, the double sum of
squared differences bounds `n·Σd²` by `(Σd)² + n²(n-2)²`. -/

private lemma spread_bound {n : ℕ} (G : Sym3Graph n) (hn : 2 ≤ n)
    (hgap : ∀ v w : Fin n, G.degree v ≤ G.degree w + (n - 2)) :
    (n : ℝ) * (∑ v : Fin n, (G.degree v : ℝ) ^ 2)
      ≤ (∑ v : Fin n, (G.degree v : ℝ)) ^ 2
        + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := by
  have hsub : ((n - 2 : ℕ) : ℝ) = (n : ℝ) - 2 := by
    rw [Nat.cast_sub hn]
    norm_num
  have hdiffle : ∀ v w : Fin n,
      (G.degree v : ℝ) - (G.degree w : ℝ) ≤ (n : ℝ) - 2 := by
    intro v w
    have h := hgap v w
    have hcast : (G.degree v : ℝ) ≤ (G.degree w : ℝ) + ((n - 2 : ℕ) : ℝ) := by
      exact_mod_cast h
    rw [hsub] at hcast
    linarith
  have hdiff : ∀ v w : Fin n,
      ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2 ≤ ((n : ℝ) - 2) ^ 2 :=
    fun v w => sq_le_sq' (by linarith [hdiffle w v]) (hdiffle v w)
  have hv : ∀ v : Fin n,
      (∑ w : Fin n, ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
        = n * (G.degree v : ℝ) ^ 2
          - 2 * (G.degree v : ℝ) * (∑ w : Fin n, (G.degree w : ℝ))
          + (∑ w : Fin n, (G.degree w : ℝ) ^ 2) := by
    intro v
    have h1 : (∑ w : Fin n, ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
        = ∑ w : Fin n, ((G.degree v : ℝ) ^ 2
            - 2 * (G.degree v : ℝ) * (G.degree w : ℝ)
            + (G.degree w : ℝ) ^ 2) :=
      Finset.sum_congr rfl fun w _ => by ring
    have h2 : (∑ w : Fin n, 2 * (G.degree v : ℝ) * (G.degree w : ℝ))
        = 2 * (G.degree v : ℝ) * (∑ w : Fin n, (G.degree w : ℝ)) := by
      rw [Finset.mul_sum]
    rw [h1, Finset.sum_add_distrib, Finset.sum_sub_distrib, h2,
      Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
  have hdouble : (∑ v : Fin n, ∑ w : Fin n,
        ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
      = 2 * n * (∑ v : Fin n, (G.degree v : ℝ) ^ 2)
        - 2 * (∑ v : Fin n, (G.degree v : ℝ)) ^ 2 := by
    have h1 : (∑ v : Fin n, ∑ w : Fin n,
          ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
        = ∑ v : Fin n, (n * (G.degree v : ℝ) ^ 2
            - 2 * (G.degree v : ℝ) * (∑ w : Fin n, (G.degree w : ℝ))
            + (∑ w : Fin n, (G.degree w : ℝ) ^ 2)) :=
      Finset.sum_congr rfl fun v _ => hv v
    have h2 : (∑ v : Fin n, (n : ℝ) * (G.degree v : ℝ) ^ 2)
        = n * (∑ v : Fin n, (G.degree v : ℝ) ^ 2) := by
      rw [Finset.mul_sum]
    have h3 : (∑ v : Fin n, 2 * (G.degree v : ℝ)
          * (∑ w : Fin n, (G.degree w : ℝ)))
        = 2 * (∑ v : Fin n, (G.degree v : ℝ))
          * (∑ w : Fin n, (G.degree w : ℝ)) := by
      have h : ∀ v : Fin n, 2 * (G.degree v : ℝ)
            * (∑ w : Fin n, (G.degree w : ℝ))
          = (2 * (∑ w : Fin n, (G.degree w : ℝ))) * (G.degree v : ℝ) :=
        fun v => by ring
      rw [Finset.sum_congr rfl fun v _ => h v, ← Finset.mul_sum]
    rw [h1, Finset.sum_add_distrib, Finset.sum_sub_distrib, h2, h3,
      Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
    ring
  have hbound : (∑ v : Fin n, ∑ w : Fin n,
        ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
      ≤ (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := by
    calc (∑ v : Fin n, ∑ w : Fin n,
          ((G.degree v : ℝ) - (G.degree w : ℝ)) ^ 2)
        ≤ ∑ _v : Fin n, ∑ _w : Fin n, ((n : ℝ) - 2) ^ 2 :=
          Finset.sum_le_sum fun v _ =>
            Finset.sum_le_sum fun w _ => hdiff v w
      _ = (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := by
          rw [Finset.sum_const, Finset.sum_const, Finset.card_univ,
            Fintype.card_fin, nsmul_eq_mul, nsmul_eq_mul]
          ring
  have hcomb : 2 * (n : ℝ) * (∑ v : Fin n, (G.degree v : ℝ) ^ 2)
      - 2 * (∑ v : Fin n, (G.degree v : ℝ)) ^ 2
      ≤ (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := hdouble ▸ hbound
  have hX : (0 : ℝ) ≤ (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := by positivity
  linarith

/-! ## The no-gap bound -/

/-- **If every degree gap is at most `n - 2`, the stationarity deficit
is at most `258/n`** — in the cleared-denominator form
`n·(P₁·D₀ - P₀·D₁) ≤ 258·D₀·D₁`. -/
private lemma noGap_count_bound {n : ℕ} (G : Sym3Graph n) (hn : 64 ≤ n)
    (hgap : ∀ v w : Fin n, G.degree v ≤ G.degree w + (n - 2)) :
    (n : ℝ) * ((G.pairCountInter 1 : ℝ) * (pairChoose n 3 3 : ℝ)
        - (G.pairCountInter 0 : ℝ) * (30 * (n.choose 5 : ℝ)))
      ≤ 258 * ((pairChoose n 3 3 : ℝ) * (30 * (n.choose 5 : ℝ))) := by
  set E : ℝ := (G.edges.card : ℝ) with hE
  set P₀ : ℝ := (G.pairCountInter 0 : ℝ) with hP₀
  set P₁ : ℝ := (G.pairCountInter 1 : ℝ) with hP₁
  set P₂ : ℝ := (G.pairCountInter 2 : ℝ) with hP₂
  set D₀ : ℝ := (pairChoose n 3 3 : ℝ) with hD₀
  set D₁ : ℝ := 30 * (n.choose 5 : ℝ) with hD₁
  set Q : ℝ := ∑ v : Fin n, (G.degree v : ℝ) ^ 2 with hQ
  -- the cast identities
  have hpart : P₀ + P₁ + P₂ + E = E * E := by
    rw [hP₀, hP₁, hP₂, hE]
    exact_mod_cast G.sum_pairCountInter
  have hdegsq : Q = 3 * E + 2 * P₂ + P₁ := by
    rw [hQ, hP₂, hP₁, hE]
    have hcast : ((∑ v : Fin n, G.degree v ^ 2 : ℕ) : ℝ)
        = ∑ v : Fin n, (G.degree v : ℝ) ^ 2 := by
      push_cast
      rfl
    rw [← hcast, G.sum_degree_sq]
    push_cast
    ring
  have hSdeg : (∑ v : Fin n, (G.degree v : ℝ)) = 3 * E := by
    rw [hE]
    have hcast : ((∑ v : Fin n, G.degree v : ℕ) : ℝ)
        = ∑ v : Fin n, (G.degree v : ℝ) := by
      push_cast
      rfl
    rw [← hcast, G.sum_degree]
    push_cast
    ring
  have h9 : 9 * D₀ = ((n : ℝ) - 5) * D₁ := by
    rw [hD₀, hD₁]
    have h := nine_pairChoose (show 6 ≤ n by omega)
    have hcast : ((9 * pairChoose n 3 3 : ℕ) : ℝ)
        = (((n - 5) * (30 * n.choose 5) : ℕ) : ℝ) := by exact_mod_cast h
    rw [Nat.cast_mul, Nat.cast_mul, Nat.cast_mul,
      Nat.cast_sub (show 5 ≤ n by omega)] at hcast
    push_cast at hcast ⊢
    linarith [hcast]
  -- the spread bound, with the degree sum substituted
  have hspread : (n : ℝ) * Q ≤ (3 * E) ^ 2
      + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 := by
    have h := spread_bound G (show 2 ≤ n by omega) hgap
    rw [hSdeg] at h
    exact h
  -- the crude bounds, cast
  have hEle : 4 * (E * E) ≤ 256 * D₀ := by
    have h1 : G.edges.card ≤ n.choose 3 := edges_card_le G
    have h2 : n.choose 3 ≤ 8 * (n - 3).choose 3 :=
      choose3_ratio (by omega)
    have h3 : G.edges.card * G.edges.card
        ≤ n.choose 3 * (8 * (n - 3).choose 3) :=
      Nat.mul_le_mul h1 (le_trans h1 h2)
    have h4 : n.choose 3 * (8 * (n - 3).choose 3)
        = 8 * pairChoose n 3 3 := by
      rw [show pairChoose n 3 3 = n.choose 3 * (n - 3).choose 3 from rfl]
      ring
    have h5 : G.edges.card * G.edges.card ≤ 8 * pairChoose n 3 3 := by
      rw [← h4]
      exact h3
    have h6 : ((G.edges.card * G.edges.card : ℕ) : ℝ)
        ≤ ((8 * pairChoose n 3 3 : ℕ) : ℝ) := by exact_mod_cast h5
    push_cast at h6
    rw [hE, hD₀]
    have h7 : (0 : ℝ) ≤ (pairChoose n 3 3 : ℝ) := Nat.cast_nonneg _
    linarith [h6]
  have hD₁ge : (n : ℝ) ^ 4 ≤ D₁ := by
    rw [hD₁]
    have h := choose5_lower hn
    exact_mod_cast h
  have hD₀ge : (n : ℝ) ^ 4 ≤ D₀ := by
    rw [hD₀]
    have h := pairChoose_lower hn
    exact_mod_cast h
  -- nonnegativity
  have hEnn : (0 : ℝ) ≤ E := by rw [hE]; positivity
  have hP₂nn : (0 : ℝ) ≤ P₂ := by rw [hP₂]; positivity
  have hD₀nn : (0 : ℝ) ≤ D₀ := by rw [hD₀]; positivity
  have hD₁nn : (0 : ℝ) ≤ D₁ := by rw [hD₁]; positivity
  have hnn : (0 : ℝ) ≤ (n : ℝ) := Nat.cast_nonneg n
  have hn2 : (2 : ℝ) ≤ (n : ℝ) := by exact_mod_cast (show 2 ≤ n by omega)
  -- the two count identities solved for `P₁` and `P₀`
  have hP₁eq : P₁ = Q - 3 * E - 2 * P₂ := by linarith
  have hP₀eq : P₀ = E * E + 2 * E + P₂ - Q := by linarith
  -- the exact rearrangement
  have hexp : P₁ * D₀ - P₀ * D₁
      = Q * (D₀ + D₁) - E * E * D₁
        - (3 * E * D₀ + 2 * P₂ * D₀ + 2 * E * D₁ + P₂ * D₁) := by
    rw [hP₁eq, hP₀eq]
    ring
  have hdropped : (0 : ℝ)
      ≤ 3 * E * D₀ + 2 * P₂ * D₀ + 2 * E * D₁ + P₂ * D₁ := by
    have h1 := mul_nonneg hEnn hD₀nn
    have h2 := mul_nonneg hP₂nn hD₀nn
    have h3 := mul_nonneg hEnn hD₁nn
    have h4 := mul_nonneg hP₂nn hD₁nn
    nlinarith [h1, h2, h3, h4]
  have hdrop : (0 : ℝ)
      ≤ (n : ℝ) * (3 * E * D₀ + 2 * P₂ * D₀ + 2 * E * D₁ + P₂ * D₁) :=
    mul_nonneg hnn hdropped
  have hDnn : (0 : ℝ) ≤ D₀ + D₁ := by linarith
  have hmul : (n : ℝ) * Q * (D₀ + D₁)
      ≤ ((3 * E) ^ 2 + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2) * (D₀ + D₁) :=
    mul_le_mul_of_nonneg_right hspread hDnn
  have h9E : 9 * (E * E) * D₀ - ((n : ℝ) - 9) * (E * E) * D₁
      = 4 * (E * E) * D₁ := by
    linear_combination (E * E) * h9
  have hsquare : (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 ≤ (n : ℝ) ^ 4 := by
    have h1 : ((n : ℝ) - 2) ^ 2 ≤ (n : ℝ) ^ 2 := by nlinarith [hn2]
    calc (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2
        ≤ (n : ℝ) ^ 2 * (n : ℝ) ^ 2 :=
          mul_le_mul_of_nonneg_left h1 (by positivity)
      _ = (n : ℝ) ^ 4 := by ring
  -- the chain
  calc (n : ℝ) * (P₁ * D₀ - P₀ * D₁)
      = (n : ℝ) * (Q * (D₀ + D₁) - E * E * D₁)
        - (n : ℝ) * (3 * E * D₀ + 2 * P₂ * D₀ + 2 * E * D₁ + P₂ * D₁) := by
        rw [hexp]
        ring
    _ ≤ (n : ℝ) * (Q * (D₀ + D₁) - E * E * D₁) := by linarith [hdrop]
    _ = (n : ℝ) * Q * (D₀ + D₁) - (n : ℝ) * (E * E) * D₁ := by ring
    _ ≤ ((3 * E) ^ 2 + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2) * (D₀ + D₁)
        - (n : ℝ) * (E * E) * D₁ := by linarith [hmul]
    _ = (9 * (E * E) * D₀ - ((n : ℝ) - 9) * (E * E) * D₁)
        + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 * (D₀ + D₁) := by ring
    _ = 4 * (E * E) * D₁
        + (n : ℝ) ^ 2 * ((n : ℝ) - 2) ^ 2 * (D₀ + D₁) := by rw [h9E]
    _ ≤ 4 * (E * E) * D₁ + (n : ℝ) ^ 4 * (D₀ + D₁) := by
        have h := mul_le_mul_of_nonneg_right hsquare hDnn
        linarith [h]
    _ ≤ 256 * D₀ * D₁ + (n : ℝ) ^ 4 * D₀ + (n : ℝ) ^ 4 * D₁ := by
        have h1 : 4 * (E * E) * D₁ ≤ 256 * D₀ * D₁ := by
          have := mul_le_mul_of_nonneg_right hEle hD₁nn
          linarith [this]
        linarith [h1]
    _ ≤ 256 * D₀ * D₁ + D₁ * D₀ + D₀ * D₁ := by
        have h1 : (n : ℝ) ^ 4 * D₀ ≤ D₁ * D₀ :=
          mul_le_mul_of_nonneg_right hD₁ge hD₀nn
        have h2 : (n : ℝ) ^ 4 * D₁ ≤ D₀ * D₁ :=
          mul_le_mul_of_nonneg_right hD₀ge hD₁nn
        linarith
    _ = 258 * (D₀ * D₁) := by ring

/-! ## The boost -/

/-- **The clone boost is a theorem**: a genuinely negative stationarity
combination forces a degree gap beyond every codegree, and cloning the
large-degree vertex over the small one strictly gains edges at the same
size. -/
theorem finiteBoost : FiniteBoost := by
  intro ε hε
  obtain ⟨N₀, hN₀⟩ := exists_nat_gt (258 / ε)
  refine ⟨max N₀ 64, ?_⟩
  intro G hNle hstat
  obtain ⟨n, Gf⟩ := G
  obtain ⟨G₀, hG₀, hGeq⟩ := exists_sym3Graph_toFlag
    (fun (M : Model hypergraph3Sig (Fin n))
      (h : TetraFree.Mem M) => h.1) Gf
  subst hGeq
  have hn64 : 64 ≤ n := le_trans (le_max_right _ _) hNle
  have hnN₀ : N₀ ≤ n := le_trans (le_max_left _ _) hNle
  by_cases hgap : ∀ v w : Fin n,
      G₀.degree v ≤ G₀.degree w + (n - 2)
  · -- no gap anywhere: the deficit is impossible at this size
    exfalso
    have hstat' : statComb ⟨n, G₀.toFlag hG₀⟩ ≤ -ε := hstat
    rw [statComb_toFlag_eq G₀ hG₀ (by omega : 6 ≤ n)] at hstat'
    have hcount := noGap_count_bound G₀ hn64 hgap
    have hD₀pos : (0 : ℝ) < (pairChoose n 3 3 : ℝ) := by
      exact_mod_cast pairChoose_pos (show 3 + 3 ≤ n by omega)
    have hc5pos : (0 : ℝ) < (n.choose 5 : ℝ) := by
      exact_mod_cast Nat.choose_pos (show 5 ≤ n by omega)
    have hD₁pos : (0 : ℝ) < 30 * (n.choose 5 : ℝ) := by linarith
    have hprod : (0 : ℝ)
        < (pairChoose n 3 3 : ℝ) * (30 * (n.choose 5 : ℝ)) :=
      mul_pos hD₀pos hD₁pos
    -- clear denominators in the stationarity deficit
    have hΔ : ε * ((pairChoose n 3 3 : ℝ) * (30 * (n.choose 5 : ℝ)))
        ≤ (G₀.pairCountInter 1 : ℝ) * (pairChoose n 3 3 : ℝ)
          - (G₀.pairCountInter 0 : ℝ) * (30 * (n.choose 5 : ℝ)) := by
      have hmul := mul_le_mul_of_nonneg_right hstat' hprod.le
      have hfield : ((G₀.pairCountInter 0 : ℝ) / (pairChoose n 3 3 : ℝ)
            - (G₀.pairCountInter 1 : ℝ) / (30 * (n.choose 5 : ℝ)))
            * ((pairChoose n 3 3 : ℝ) * (30 * (n.choose 5 : ℝ)))
          = (G₀.pairCountInter 0 : ℝ) * (30 * (n.choose 5 : ℝ))
            - (G₀.pairCountInter 1 : ℝ) * (pairChoose n 3 3 : ℝ) := by
        field_simp
      rw [hfield] at hmul
      linarith [hmul]
    -- combine: `n·ε ≤ 258`, against `258/ε < N₀ ≤ n`
    have hnε : (n : ℝ) * ε ≤ 258 := by
      have h1 : (n : ℝ) * (ε * ((pairChoose n 3 3 : ℝ)
            * (30 * (n.choose 5 : ℝ))))
          ≤ (n : ℝ) * ((G₀.pairCountInter 1 : ℝ)
              * (pairChoose n 3 3 : ℝ)
            - (G₀.pairCountInter 0 : ℝ) * (30 * (n.choose 5 : ℝ))) :=
        mul_le_mul_of_nonneg_left hΔ (Nat.cast_nonneg _)
      have h2 := le_trans h1 hcount
      by_contra h258
      push_neg at h258
      have h3 := mul_lt_mul_of_pos_right h258 hprod
      nlinarith [h2, h3]
    have hgt : 258 / ε < (n : ℝ) :=
      lt_of_lt_of_le hN₀ (by exact_mod_cast hnN₀)
    rw [div_lt_iff₀ hε] at hgt
    linarith
  · -- a genuine gap: clone across it
    push_neg at hgap
    obtain ⟨u, w, hgap⟩ := hgap
    have huw : u ≠ w := by
      intro h
      rw [h] at hgap
      omega
    have hclone : G₀.edges.card < (G₀.cloneAt u w huw).edges.card := by
      refine G₀.card_cloneAt_gt huw ?_
      have hco := G₀.codegree_le huw
      show (G₀.edges.filter fun e => w ∈ e).card + G₀.codegree u w
        < (G₀.edges.filter fun e => u ∈ e).card
      have h1 : (G₀.edges.filter fun e => w ∈ e).card = G₀.degree w := rfl
      have h2 : (G₀.edges.filter fun e => u ∈ e).card = G₀.degree u := rfl
      omega
    refine ⟨(G₀.cloneAt u w huw).toFlag (cloneAt_mem huw hG₀), ?_⟩
    show edgeDens ⟨n, G₀.toFlag hG₀⟩
      < edgeDens ⟨n, (G₀.cloneAt u w huw).toFlag (cloneAt_mem huw hG₀)⟩
    rw [edgeDens_toFlag, edgeDens_toFlag]
    have hC : (0 : ℝ) < (n.choose 3 : ℝ) := by
      exact_mod_cast Nat.choose_pos (show 3 ≤ n by omega)
    have hlt : (G₀.edges.card : ℝ)
        < ((G₀.cloneAt u w huw).edges.card : ℝ) := by
      exact_mod_cast hclone
    rw [div_eq_mul_inv, div_eq_mul_inv]
    exact mul_lt_mul_of_pos_right hlt (inv_pos.mpr hC)

/-! ## The unconditional bound -/

/-- **The finite Turán density of the tetrahedron obeys the order-7
certificate bound, through the finite cloning boost**: no hypotheses
remain. -/
theorem turanDensity_le_certBound_finite :
    turanDensity ≤ ((certBound : ℚ) : ℝ) :=
  turanDensity_le_certBound maxDensAntitone finiteBoost

/-- The bound, numerically: below the published record `1123/2000`. -/
theorem turanDensity_lt_published_finite :
    turanDensity < (1123 / 2000 : ℝ) := by
  refine lt_of_le_of_lt turanDensity_le_certBound_finite ?_
  rw [certBound_cast]
  norm_num

/-- The elementary headline through the finite route: the Turán density of
the tetrahedron is at most the certificate value `312372062889819 / 560000000000000`. -/
theorem tetraTuranDensity_le_certValue_finite :
    tetraTuranDensity ≤ 312372062889819 / 560000000000000 := by
  rw [tetraTuranDensity_eq]
  exact turanDensity_le_certBound_finite.trans_eq certBound_cast

/-- The comparison form through the finite route. -/
theorem tetraTuranDensity_lt_published_finite :
    tetraTuranDensity < 1123 / 2000 := by
  rw [tetraTuranDensity_eq]
  exact turanDensity_lt_published_finite

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
