import LeanFlagAlgebras.Core.Compute.Mask3

-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py from certificate/K4_turan_order7_certificate.json;
-- see manifest.json for the certificate hash.
-- 7 rows; entries shifted by 10597207 into the naturals.
namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

set_option maxHeartbeats 4000000
set_option maxRecDepth 200000

private def f7s1RawP0 : List ℕ :=
  [10420247, 13938980, 17655110, 21194413, 523750, 3475721, 7146167, 10921835, 10655571, 10829528,
   9367089, 9288521, 10770952, 10796319, 10351842, 10990280, 10344930, 10527539, 10577415, 10347354,
   10833903, 10937245, 10687322, 10513878, 10577440, 10662791, 10447672, 10553053, 10601524, 10554132,
   10541034, 10619959, 10566444, 10591624, 10611575, 10594846, 10586098, 10604143, 10591786, 10601366,
   10582016, 10603317, 10597200, 10597205, 10597201, 10597200, 10597207, 10597201, 10597187]

def f7s1Raw : List ℕ :=
  f7s1RawP0

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
