-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7ClassIdx.lean; certificate-dependent imports redirected.
import Mathlib.Algebra.BigOperators.Fin
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Chain
import LeanFlagAlgebras.Core.Examples.TetrahedronOrder7Distinct
import LeanFlagAlgebras.Core.Examples.TetrahedronOrder7Complete

/-! # The class-index table computes the flag class

The certificate turns a six-vertex mask into a number by looking it up
in `classIdxTable` and reading the corresponding `classNums` entry. For
that to be a statement about flag classes rather than about masks, the
table has to return the position of a representative isomorphic to the
mask. It does, and this file proves it.

The table is built by spreading each representative over its orbit, so
the cheap direction is checked directly: on every one of the
`964 * 720` orbit images the table returns the representative's index.
Completeness of the listing and the orbit description of isomorphism
then cover every tetrahedron-free mask.

With that, the certificate's deck sum becomes a sum over the seven
deleted vertices of a class number — the shape the chain rule
consumes. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-! ## The table is the class index -/

/-- The table names each representative on its whole orbit. -/
lemma classIdxTable_orbit_all :
    ((List.range 964).all fun i =>
      (List.range 720).all fun k =>
        classIdxTable.getD (rankApply (getRank k) (h6Reps.getD i 0)) 9999 == i)
      = true := by
  native_decide

lemma classIdxTable_of_orbit {i k : ℕ} (hi : i < 964) (hk : k < 720) :
    classIdxTable.getD (rankApply (getRank k) (h6Reps.getD i 0)) 9999 = i := by
  have h1 := List.all_eq_true.mp classIdxTable_orbit_all i
    (List.mem_range.mpr hi)
  have h2 := List.all_eq_true.mp h1 k (List.mem_range.mpr hk)
  simpa using h2

/-- **The class index is the flag class**: on a tetrahedron-free
six-vertex mask the table returns the position of a representative
isomorphic to it. -/
theorem classIdxTable_spec {h : ℕ} (hh : h < 2 ^ 20)
    (hk4 : k4FreeMask (quadIdxList 6) h = true) :
    classIdxTable.getD h 9999 < 964
      ∧ (graphOfMask 6 h).IsIso
          (graphOfMask 6 (h6Reps.getD (classIdxTable.getD h 9999) 0)) := by
  obtain ⟨r, hrmem, hiso⟩ := h6Reps_complete hh hk4
  obtain ⟨i, hi, hri⟩ : ∃ i, i < 964 ∧ h6Reps.getD i 0 = r := by
    obtain ⟨i, hi, hget⟩ := List.mem_iff_getElem.mp hrmem
    exact ⟨i, by rwa [h6Reps_length] at hi,
      by rw [List.getD_eq_getElem _ _ hi, hget]⟩
  have hmem : h ∈ orbitOf r := mem_orbitOf_of_isIso hh (isIso_symm hiso)
  obtain ⟨k, hk, hkeq⟩ := List.mem_map.mp hmem
  have hidx : classIdxTable.getD h 9999 = i := by
    rw [← hkeq, ← hri]
    exact classIdxTable_of_orbit hi (List.mem_range.mp hk)
  rw [hidx, hri]
  exact ⟨hi, hiso⟩

/-! ## The stored class numbers -/

private lemma getD_toArray (l : List ℤ) (i : ℕ) (d : ℤ) :
    l.toArray.getD i d = l.getD i d := by
  simp only [Array.getD, List.getD]
  by_cases h : i < l.length
  · rw [dif_pos (by simpa using h), List.getElem?_eq_getElem h]
    rfl
  · rw [dif_neg (by simpa using h), List.getElem?_eq_none (by omega)]
    rfl

lemma classNums_getD {i : ℕ} (hi : i < 964) :
    classNums.getD i 0 = classNum (h6Reps.getD i 0) := by
  have hlen : i < h6Reps.length := by rw [h6Reps_length]; exact hi
  have hmap : i < (h6Reps.map classNum).length := by
    rw [List.length_map]; exact hlen
  rw [classNums, getD_toArray, List.getD_eq_getElem _ _ hmap,
    List.getD_eq_getElem _ _ hlen, List.getElem_map]

/-! ## The deck is a legitimate six-vertex mask -/

lemma deckMask_lt (v : Fin 7) (m : ℕ) : deckMask v m < 2 ^ 20 := by
  refine Nat.lt_pow_two_of_testBit _ fun i hi => ?_
  rw [deckMask, gatherBits_testBit, decide_eq_false (by omega : ¬ i < 20)]
  simp

/-- **Tetrahedron-freeness is inherited by every deck.** -/
theorem deckMask_k4Free (v : Fin 7) {m : ℕ}
    (hm : k4FreeMask (quadIdxList 7) m = true) :
    k4FreeMask (quadIdxList 6) (deckMask v m) = true := by
  rw [k4FreeMask_iff_testBit] at hm ⊢
  intro a b c d hab hbc hcd hd hbits
  have ha6 : a < 6 := by omega
  have hb6 : b < 6 := by omega
  have hc6 : c < 6 := by omega
  have key : ∀ x y z : Fin 6, x < y → y < z →
      (deckMask v m).testBit (triIdx 6 x.val y.val z.val)
        = m.testBit (triIdx 7 (v.succAbove x).val (v.succAbove y).val
            (v.succAbove z).val) :=
    fun x y z hxy hyz => deckMask_testBit v m hxy hyz
  have hA : (⟨a, ha6⟩ : Fin 6) < ⟨b, hb6⟩ := Fin.lt_def.mpr hab
  have hB : (⟨b, hb6⟩ : Fin 6) < ⟨c, hc6⟩ := Fin.lt_def.mpr hbc
  have hC : (⟨c, hc6⟩ : Fin 6) < ⟨d, hd⟩ := Fin.lt_def.mpr hcd
  refine hm (v.succAbove ⟨a, ha6⟩).val (v.succAbove ⟨b, hb6⟩).val
    (v.succAbove ⟨c, hc6⟩).val (v.succAbove ⟨d, hd⟩).val
    (Fin.lt_def.mp (Fin.succAbove_lt_succAbove_iff.mpr hA))
    (Fin.lt_def.mp (Fin.succAbove_lt_succAbove_iff.mpr hB))
    (Fin.lt_def.mp (Fin.succAbove_lt_succAbove_iff.mpr hC))
    (Fin.isLt _) ⟨?_, ?_, ?_, ?_⟩
  · rw [← key _ _ _ hA hB]; exact hbits.1
  · rw [← key _ _ _ hA (hB.trans hC)]; exact hbits.2.1
  · rw [← key _ _ _ (hA.trans hB) hC]; exact hbits.2.2.1
  · rw [← key _ _ _ hB hC]; exact hbits.2.2.2

/-! ## The deck sum -/

set_option maxRecDepth 8192 in
/-- The seven-entry gather fold, written out. Keeping the summand
abstract is what stops the kernel from trying to evaluate the
million-entry class table. -/
private lemma foldl_deckGathersA (F : ℕ → ℤ) :
    deckGathersA.foldl (fun acc g => acc + F g) 0
      = F (deckGathers.getD 0 0) + F (deckGathers.getD 1 0)
        + F (deckGathers.getD 2 0) + F (deckGathers.getD 3 0)
        + F (deckGathers.getD 4 0) + F (deckGathers.getD 5 0)
        + F (deckGathers.getD 6 0) := by
  show (0 : ℤ) + F _ + F _ + F _ + F _ + F _ + F _ + F _ = _
  rw [zero_add]
  rfl

/-- The certificate's deck fold, as a sum over the deleted vertices. -/
theorem deckValue_eq_sum (m : ℕ) :
    deckValue m = ∑ v : Fin 7,
      classNums.getD (classIdxTable.getD (deckMask v m) 9999) 0 := by
  rw [Fin.sum_univ_seven, deckValue,
    foldl_deckGathersA fun g =>
      classNums.getD (classIdxTable.getD (gatherBits g 20 m) 9999) 0]
  rfl

/-- **The deck sum is a sum of class numbers of representatives**: each
term is the class number of a listed representative isomorphic to the
corresponding deck. -/
theorem deckValue_eq_sum_classNum {m : ℕ}
    (hk4 : k4FreeMask (quadIdxList 7) m = true) :
    deckValue m = ∑ v : Fin 7,
      classNum (h6Reps.getD (classIdxTable.getD (deckMask v m) 9999) 0) := by
  rw [deckValue_eq_sum]
  refine Finset.sum_congr rfl fun v _ => ?_
  exact classNums_getD
    (classIdxTable_spec (deckMask_lt v m) (deckMask_k4Free v hk4)).1

/-- Each deck's representative is isomorphic to the deck, hence to the
induced subgraph on the other six vertices. -/
theorem isIso_deck_rep (v : Fin 7) {m : ℕ}
    (hk4 : k4FreeMask (quadIdxList 7) m = true) :
    ((graphOfMask 7 m).pullback v.succAbove).IsIso
      (graphOfMask 6 (h6Reps.getD (classIdxTable.getD (deckMask v m) 9999) 0)) := by
  rw [← graphOfMask_deckMask]
  exact (classIdxTable_spec (deckMask_lt v m) (deckMask_k4Free v hk4)).2

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
