-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7BlockCheck.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7BlockGamma

/-! # The block folds compute the rooting sums

The certificate's `blockValue` folds walk the splits tables; the
abstract side's rooting sums walk the well-formed rootings. This file
checks, one representative at a time, that they agree — which
discharges, in one sweep, the splits tables' enumeration, the inverse
tables' lookups, and the dispatch by root mask.

`S45C`/`S24C` sum the per-row rooting sums over the stored factor rows;
the check is exact integer arithmetic per class. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-- The total 45-side rooting sum over all four families and their
rows. -/
def S45C (r : ℕ) : ℚ :=
  (facs45_0L.map fun row => s45C 0 flags45_0 row r).sum
    + (facs45_1L.map fun row => s45C 1 flags45_1 row r).sum
    + (facs45_3L.map fun row => s45C 3 flags45_3 row r).sum
    + (facs45_7L.map fun row => s45C 7 flags45_7 row r).sum

/-- The total 24-side rooting sum over its rows. -/
def S24C (r : ℕ) : ℚ :=
  (facs24L.map fun row => s24C row r).sum

set_option maxHeartbeats 1000000 in
/-- **The certificate's block folds are the rooting sums**, on every
listed representative. -/
lemma blockValue_check :
    (h6Reps.all fun h =>
      decide ((blockValue24 h : ℚ) = S24C h)
        && decide ((blockValue45 h : ℚ) = S45C h)) = true := by
  native_decide

lemma blockValue24_eq_of_mem {h : ℕ} (hh : h ∈ h6Reps) :
    (blockValue24 h : ℚ) = S24C h := by
  have := List.all_eq_true.mp blockValue_check h hh
  rw [Bool.and_eq_true] at this
  exact of_decide_eq_true this.1

lemma blockValue45_eq_of_mem {h : ℕ} (hh : h ∈ h6Reps) :
    (blockValue45 h : ℚ) = S45C h := by
  have := List.all_eq_true.mp blockValue_check h hh
  rw [Bool.and_eq_true] at this
  exact of_decide_eq_true this.2

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
