-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Extension.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.TetrahedronOrder7Data
import LeanFlagAlgebras.Core.Examples.TetrahedronMask

/-! # Seven-vertex extensions of the six-vertex representatives

The order-7 certificate is checked on every admissible labeled
seven-vertex one-point extension of a representative: a listed
representative `h` on vertices `0`–`5` together with a *link* — the set
of pairs `{a, b}` for which `{a, b, 6}` is a hyperedge — subject to the
extension staying tetrahedron-free.

`extendMask` assembles the seven-vertex mask from the two halves by
transporting bits along the position tables, so admissibility is just
`k4FreeMask` at seven vertices and its meaning transfers through
`k4FreeMask_iff_mem` with no further bridge.

The count recorded here, `13051375`, is the number the certificate's
oracle checks; reproducing it independently pins the enumeration
convention (new vertex last, links as pairs in lexicographic order)
before any certificate arithmetic is attempted. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-- Positions of the six-vertex triples inside the seven-vertex
ranking, as `(source rank, target rank)` pairs. -/
def remapPairs : List (ℕ × ℕ) :=
  [(0, 0), (1, 1), (2, 2), (3, 3), (4, 5),
   (5, 6), (6, 7), (7, 9), (8, 10), (9, 12),
   (10, 15), (11, 16), (12, 17), (13, 19), (14, 20),
   (15, 22), (16, 25), (17, 26), (18, 28), (19, 31)]

/-- Positions of the link triples `{a, b, 6}` inside the seven-vertex
ranking, indexed by the lexicographic rank of the pair `{a, b}`. -/
def linkPairs : List (ℕ × ℕ) :=
  [(0, 4), (1, 8), (2, 11), (3, 13), (4, 14),
   (5, 18), (6, 21), (7, 23), (8, 24), (9, 27),
   (10, 29), (11, 30), (12, 32), (13, 33), (14, 34)]

/-- The quadruple table of the seven-vertex range, as a literal. -/
def qs7 : List (ℕ × ℕ × ℕ × ℕ) :=
  [(0, 1, 5, 15), (0, 2, 6, 16), (0, 3, 7, 17),
   (0, 4, 8, 18), (1, 2, 9, 19), (1, 3, 10, 20),
   (1, 4, 11, 21), (2, 3, 12, 22), (2, 4, 13, 23),
   (3, 4, 14, 24), (5, 6, 9, 25), (5, 7, 10, 26),
   (5, 8, 11, 27), (6, 7, 12, 28), (6, 8, 13, 29),
   (7, 8, 14, 30), (9, 10, 12, 31), (9, 11, 13, 32),
   (10, 11, 14, 33), (12, 13, 14, 34), (15, 16, 19, 25),
   (15, 17, 20, 26), (15, 18, 21, 27), (16, 17, 22, 28),
   (16, 18, 23, 29), (17, 18, 24, 30), (19, 20, 22, 31),
   (19, 21, 23, 32), (20, 21, 24, 33), (22, 23, 24, 34),
   (25, 26, 28, 31), (25, 27, 29, 32), (26, 27, 30, 33),
   (28, 29, 30, 34), (31, 32, 33, 34)]

set_option maxRecDepth 8192 in
lemma qs7_eq : qs7 = quadIdxList 7 := by decide

/-- Transport a set of bits along a position table. -/
def spread (tbl : List (ℕ × ℕ)) (bits acc : ℕ) : ℕ :=
  tbl.foldl (fun a p => if bits.testBit p.1 then a ||| (1 <<< p.2) else a) acc

/-- The seven-vertex mask of a representative extended by a link. -/
def extendMask (h link : ℕ) : ℕ :=
  spread linkPairs link (spread remapPairs h 0)

/-- A link is admissible when the extension stays tetrahedron-free. -/
def extAdmissible (h link : ℕ) : Bool :=
  k4FreeMask qs7 (extendMask h link)

/-- Admissibility is membership in the theory, through the mask
bridge. -/
lemma extAdmissible_iff_mem {h link : ℕ} :
    extAdmissible h link = true
      ↔ TetraFree.Mem (graphOfMask 7 (extendMask h link)).toModel := by
  rw [extAdmissible, qs7_eq, k4FreeMask_iff_mem]

/-- Count the admissible links of one representative. -/
def countLinksFrom (h : ℕ) : ℕ → ℕ → ℕ
  | 0, acc => acc
  | n + 1, acc => countLinksFrom h n (if extAdmissible h n then acc + 1 else acc)

/-- The admissible links of one representative, all `2 ^ 15` of them. -/
def countLinks (h : ℕ) : ℕ := countLinksFrom h 32768 0

/-- The admissible labeled seven-vertex extensions of the whole
listing. -/
def countExtensions : ℕ := (h6Reps.map countLinks).sum

/-- **The extension count matches the certificate's oracle**: the
enumeration convention is pinned. -/
lemma countExtensions_eq : countExtensions = 13051375 := by
  native_decide

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
