-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronLimitHom.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronLimitMul

/-! # The limit homomorphism

The assembly: along a realizing sequence the limit functional is
multiplicative — on basis classes by the pair chain rule in the limit,
in general by bilinearity — sends the unit to one, and is nonnegative
on flags. Packaged, that is a positive homomorphism realized by the
sequence, and with subsequence compactness every size-blowing sequence
of finite flags has a realized subsequence: the limit half of
Razborov's Theorem 3.3. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core Filter

/-- The linear extension as a support sum. -/
lemma limitLin_apply (L : FinFlag TetraFree emptyType → ℝ)
    (f : FlagVector TetraFree emptyType) :
    limitLin L f = ∑ F ∈ f.support, f F * L F := by
  rw [limitLin, Finsupp.linearCombination_apply, Finsupp.sum]
  exact Finset.sum_congr rfl fun F _ => smul_eq_mul _ _

section Realizing

variable (Gs : ℕ → FinFlag TetraFree emptyType)
    (L : FinFlag TetraFree emptyType → ℝ)
    (hsz : Tendsto (fun k => (Gs k).1) atTop atTop)
    (hconv : ∀ F : FinFlag TetraFree emptyType,
      Tendsto (fun k => ((subflagDensity F.2 (Gs k).2 : ℚ) : ℝ))
        atTop (nhds (L F)))

include hsz hconv in
/-- **Basis multiplicativity**: the limit functional evaluates a flag
product to the product of the values. -/
lemma limitLin_flagMul (F₁ F₂ : FinFlag TetraFree emptyType) :
    limitLin L (flagMul F₁ F₂) = L F₁ * L F₂ := by
  rw [flagMul]
  rw [show F₁.1 + F₂.1 - Fintype.card (Fin 0) = F₁.1 + F₂.1 from by
    simp]
  rw [flagMulWithSize, map_sum]
  rw [Finset.sum_congr rfl fun G (_ : G ∈ Finset.univ) => by
    rw [map_smul, limitLin_basis, smul_eq_mul]]
  exact pairChain_limit Gs L hsz hconv F₁ F₂

include hsz hconv in
/-- **Full multiplicativity** of the descent, by bilinearity. -/
lemma limitQuot_mul {hC : ChainClosed L}
    (x y : FlagAlgebra TetraFree emptyType) :
    limitQuot hC (x * y) = limitQuot hC x * limitQuot hC y := by
  refine Quotient.inductionOn₂ x y fun f g => ?_
  rw [← mul_quot, limitQuot_mk, limitQuot_mk, limitQuot_mk,
    flagVector_mul_eq_nested_sum, map_sum]
  rw [Finset.sum_congr rfl fun F (_ : F ∈ f.support) => by
    rw [map_sum,
      Finset.sum_congr rfl fun G (_ : G ∈ g.support) => by
        rw [map_smul, limitLin_flagMul Gs L hsz hconv, smul_eq_mul]]]
  rw [limitLin_apply, limitLin_apply, Finset.sum_mul_sum]
  refine Finset.sum_congr rfl fun F _ => ?_
  refine Finset.sum_congr rfl fun G _ => ?_
  ring

include hconv in
/-- **The unit value is one** along a realizing sequence. -/
lemma limit_one : L 1 = 1 := by
  refine tendsto_nhds_unique (hconv 1) ?_
  have hone : ∀ k : ℕ,
      ((subflagDensity (1 : FinFlag TetraFree emptyType).2 (Gs k).2
        : ℚ) : ℝ) = 1 := by
    intro k
    rw [finFlag_one_snd, subflagDensity_unitFlag]
    norm_num
  refine Tendsto.congr (fun k => (hone k).symm) ?_
  exact tendsto_const_nhds

end Realizing

/-- **The limit homomorphism**: the descent packaged as a positive
homomorphism. -/
noncomputable def limitHom (Gs : ℕ → FinFlag TetraFree emptyType)
    (L : FinFlag TetraFree emptyType → ℝ)
    (hsz : Tendsto (fun k => (Gs k).1) atTop atTop)
    (hconv : ∀ F : FinFlag TetraFree emptyType,
      Tendsto (fun k => ((subflagDensity F.2 (Gs k).2 : ℚ) : ℝ))
        atTop (nhds (L F)))
    (hC : ChainClosed L) : PositiveHom TetraFree emptyType := by
  refine ⟨AlgHom.mk' ⟨⟨⟨limitQuot hC, ?_⟩, ?_⟩, ?_, ?_⟩ ?_, ?_⟩
  · rw [limitQuot_one hC]
    exact limit_one Gs L hconv
  · exact fun x y => limitQuot_mul Gs L hsz hconv (hC := hC) x y
  · show limitQuot hC 0 = 0
    show limitQuot hC ⟦0⟧ = 0
    rw [limitQuot_mk, map_zero]
  · exact fun x y => limitQuot_add hC x y
  · intro c x
    show limitQuot hC (c • x) = c • limitQuot hC x
    rw [limitQuot_smul hC c x]
    rfl
  · intro F
    show 0 ≤ limitQuot hC ⟦basisVector F⟧
    rw [limitQuot_basis]
    exact limit_nonneg Gs L hconv F

@[simp]
lemma limitHom_basis (Gs : ℕ → FinFlag TetraFree emptyType)
    (L : FinFlag TetraFree emptyType → ℝ)
    (hsz : Tendsto (fun k => (Gs k).1) atTop atTop)
    (hconv : ∀ F : FinFlag TetraFree emptyType,
      Tendsto (fun k => ((subflagDensity F.2 (Gs k).2 : ℚ) : ℝ))
        atTop (nhds (L F)))
    (hC : ChainClosed L) (F : FinFlag TetraFree emptyType) :
    limitHom Gs L hsz hconv hC ⟦basisVector F⟧ = L F :=
  limitQuot_basis hC F

/-- **The limit homomorphism is realized by the sequence.** -/
theorem limitHom_realizedBy (Gs : ℕ → FinFlag TetraFree emptyType)
    (L : FinFlag TetraFree emptyType → ℝ)
    (hsz : Tendsto (fun k => (Gs k).1) atTop atTop)
    (hconv : ∀ F : FinFlag TetraFree emptyType,
      Tendsto (fun k => ((subflagDensity F.2 (Gs k).2 : ℚ) : ℝ))
        atTop (nhds (L F)))
    (hC : ChainClosed L) :
    RealizedBy (limitHom Gs L hsz hconv hC) Gs := by
  refine ⟨hsz, fun F => ?_⟩
  rw [limitHom_basis]
  exact hconv F

/-- **The limit half of realization**: every size-blowing sequence of
finite flags has a subsequence realizing a positive homomorphism. -/
theorem exists_realized_subseq (Gs : ℕ → FinFlag TetraFree emptyType)
    (hsz : Tendsto (fun k => (Gs k).1) atTop atTop) :
    ∃ s : ℕ → ℕ, StrictMono s
      ∧ ∃ ψ : PositiveHom TetraFree emptyType,
          RealizedBy ψ (fun k => Gs (s k)) := by
  obtain ⟨s, hs, hsz', L, hconv⟩ := exists_convergent_subseq Gs hsz
  have hC : ChainClosed L :=
    chainClosed_of_tendsto (fun k => Gs (s k)) L hsz' hconv
  exact ⟨s, hs, limitHom (fun k => Gs (s k)) L hsz' hconv hC,
    limitHom_realizedBy (fun k => Gs (s k)) L hsz' hconv hC⟩

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
