-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7RootScaled.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootExpand
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7RootExpand
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7RootMatch
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7RootElt

/-! # The root element is the scaled root SOS element

The final identification: expanding each downward square of `rootSOS`
over the seven-vertex classes, evaluating every fiber sum at the
class's bounded representative, and replacing the rooting sums by the
certificate's folds through the matches, the coefficient of every class
is exactly the certificate's rooted value over the column denominator —
which is `rootElt`'s coefficient times `D²`. So `IsRootScaled` holds,
and with it the order-7 semidefinite part and the bound itself become
unconditional in everything but degree stationarity. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

open Classical

/-! ## List bookkeeping -/

private lemma sum_list_swap' {α : Type}
    (l : List α) (g : α → FlagWithSize TetraFree emptyType 7 →
      FlagAlgebra TetraFree emptyType) :
    (l.map fun a => ∑ H : FlagWithSize TetraFree emptyType 7, g a H).sum
      = ∑ H : FlagWithSize TetraFree emptyType 7,
          (l.map fun a => g a H).sum := by
  induction l with
  | nil => simp
  | cons a t ih =>
    rw [List.map_cons, List.sum_cons, ih, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun H _ => ?_
    rw [List.map_cons, List.sum_cons]

private lemma map_smul_sum' {α : Type} (l : List α) (c : α → ℝ)
    (x : FlagAlgebra TetraFree emptyType) :
    (l.map fun a => c a • x).sum = (l.map c).sum • x := by
  induction l with
  | nil => simp
  | cons a t ih =>
    rw [List.map_cons, List.sum_cons, ih, List.map_cons, List.sum_cons,
      add_smul]

private lemma listRangeSumR (n : ℕ) (f : ℕ → ℝ) :
    ((List.range n).map f).sum = ∑ r ∈ Finset.range n, f r := by
  induction n with
  | zero => simp
  | succ k ih =>
    rw [List.range_succ, List.map_append, List.sum_append,
      List.map_cons, List.map_nil, List.sum_cons, List.sum_nil,
      ih, Finset.sum_range_succ]
    ring

/-! ## The per-family coefficient sums -/

private lemma famS1 (H : FlagWithSize TetraFree emptyType 7) :
    (∑ r ∈ Finset.range 7, (1 / 7 : ℝ)
        * ∑ θ ∈ rootingsOf vertexGraph (graphOfMask 7 (boundedRep H)),
          ((((∑ p ∈ outsideTriples θ,
              (∑ i : Fin 7, ((fS1 r i.val : ℤ) : ℚ)
                  * (if (s1Flag i.val).IsIso (extFlagS1
                      (graphOfMask 7 (boundedRep H)) θ
                      p.1.1 p.1.2.1 p.1.2.2) then 1 else 0))
                * (∑ j : Fin 7, ((fS1 r j.val : ℤ) : ℚ)
                    * (if (s1Flag j.val).IsIso (extFlagS1
                        (graphOfMask 7 (boundedRep H)) θ
                        p.2.1 p.2.2.1 p.2.2.2) then 1 else 0)))
              / 20 : ℚ)) : ℝ))
      = (1 / 140 : ℝ) * ((s1Value (boundedRep H) : ℤ) : ℚ) := by
  rw [s1_match (boundedRep_mem H)]
  push_cast
  rw [Finset.mul_sum]
  refine Finset.sum_congr rfl fun r _ => ?_
  rw [Finset.mul_sum, Finset.mul_sum]
  refine Finset.sum_congr rfl fun θ _ => ?_
  ring

private lemma famS3 (H : FlagWithSize TetraFree emptyType 7) :
    ((∑ r ∈ Finset.range 236, (1 / 210 : ℝ)
        * ∑ θ ∈ rootingsOf (s3Type 0) (graphOfMask 7 (boundedRep H)),
          ((((∑ p ∈ outsidePairsS3 θ,
              (∑ i : Fin 236, ((fS30 r i.val : ℤ) : ℚ)
                  * (if (s30Flag i.val).IsIso (extFlagS3
                      (graphOfMask 7 (boundedRep H)) θ p.1.1 p.1.2)
                    then 1 else 0))
                * (∑ j : Fin 236, ((fS30 r j.val : ℤ) : ℚ)
                    * (if (s30Flag j.val).IsIso (extFlagS3
                        (graphOfMask 7 (boundedRep H)) θ p.2.1 p.2.2)
                      then 1 else 0))) / 6 : ℚ)) : ℝ))
      + ∑ r ∈ Finset.range 187, (1 / 210 : ℝ)
          * ∑ θ ∈ rootingsOf (s3Type 1) (graphOfMask 7 (boundedRep H)),
            ((((∑ p ∈ outsidePairsS3 θ,
                (∑ i : Fin 191, ((fS31 r i.val : ℤ) : ℚ)
                    * (if (s31Flag i.val).IsIso (extFlagS3
                        (graphOfMask 7 (boundedRep H)) θ p.1.1 p.1.2)
                      then 1 else 0))
                  * (∑ j : Fin 191, ((fS31 r j.val : ℤ) : ℚ)
                      * (if (s31Flag j.val).IsIso (extFlagS3
                          (graphOfMask 7 (boundedRep H)) θ p.2.1 p.2.2)
                        then 1 else 0))) / 6 : ℚ)) : ℝ))
      = (1 / 1260 : ℝ) * ((s3Value (boundedRep H) : ℤ) : ℚ) := by
  rw [s3_match (boundedRep_mem H)]
  push_cast
  rw [mul_add, Finset.mul_sum, Finset.mul_sum]
  refine congrArg₂ (· + ·) ?_ ?_ <;>
    · refine Finset.sum_congr rfl fun r _ => ?_
      rw [Finset.mul_sum, Finset.mul_sum]
      refine Finset.sum_congr rfl fun θ _ => ?_
      ring

/-! ## The identification -/

/-- **The order-7 coefficient identity holds**: the certificate's rooted
element is the root SOS element over `D²`. -/
theorem oldRootElt_eq_scaled :
    oldRootElt = ((1 : ℝ) / 4000000000000) • oldRootSOS := by
  show oldRootElt = ((1 : ℝ) / 4000000000000) • oldRootSOS
  have hexp : oldRootSOS
      = ∑ H : FlagWithSize TetraFree emptyType 7,
          ((∑ r ∈ Finset.range 7, (1 / 7 : ℝ)
              * ∑ θ ∈ rootingsOf vertexGraph
                  (graphOfMask 7 (boundedRep H)),
                ((((∑ p ∈ outsideTriples θ,
                    (∑ i : Fin 7, ((fS1 r i.val : ℤ) : ℚ)
                        * (if (s1Flag i.val).IsIso (extFlagS1
                            (graphOfMask 7 (boundedRep H)) θ
                            p.1.1 p.1.2.1 p.1.2.2) then 1 else 0))
                      * (∑ j : Fin 7, ((fS1 r j.val : ℤ) : ℚ)
                          * (if (s1Flag j.val).IsIso (extFlagS1
                              (graphOfMask 7 (boundedRep H)) θ
                              p.2.1 p.2.2.1 p.2.2.2) then 1 else 0)))
                    / 20 : ℚ)) : ℝ))
            + (∑ r ∈ Finset.range 236, (1 / 210 : ℝ)
                * ∑ θ ∈ rootingsOf (s3Type 0)
                    (graphOfMask 7 (boundedRep H)),
                  ((((∑ p ∈ outsidePairsS3 θ,
                      (∑ i : Fin 236, ((fS30 r i.val : ℤ) : ℚ)
                          * (if (s30Flag i.val).IsIso (extFlagS3
                              (graphOfMask 7 (boundedRep H)) θ
                              p.1.1 p.1.2) then 1 else 0))
                        * (∑ j : Fin 236, ((fS30 r j.val : ℤ) : ℚ)
                            * (if (s30Flag j.val).IsIso (extFlagS3
                                (graphOfMask 7 (boundedRep H)) θ
                                p.2.1 p.2.2) then 1 else 0))) / 6 : ℚ))
                    : ℝ))
            + ∑ r ∈ Finset.range 187, (1 / 210 : ℝ)
                * ∑ θ ∈ rootingsOf (s3Type 1)
                    (graphOfMask 7 (boundedRep H)),
                  ((((∑ p ∈ outsidePairsS3 θ,
                      (∑ i : Fin 191, ((fS31 r i.val : ℤ) : ℚ)
                          * (if (s31Flag i.val).IsIso (extFlagS3
                              (graphOfMask 7 (boundedRep H)) θ
                              p.1.1 p.1.2) then 1 else 0))
                        * (∑ j : Fin 191, ((fS31 r j.val : ℤ) : ℚ)
                            * (if (s31Flag j.val).IsIso (extFlagS3
                                (graphOfMask 7 (boundedRep H)) θ
                                p.2.1 p.2.2) then 1 else 0))) / 6 : ℚ))
                    : ℝ)) •
            (⟦basisVector (⟨7, H⟩ : FinFlag TetraFree emptyType)⟧
              : FlagAlgebra TetraFree emptyType) := by
    have hs : oldRootSOS
        = ((List.range 7).map fun r => downward (xS1 r * xS1 r)).sum
          + ((List.range 236).map fun r =>
              downward (xS30 r * xS30 r)).sum
          + ((List.range 187).map fun r =>
              downward (xS31 r * xS31 r)).sum := rfl
    rw [hs,
      List.map_congr_left fun r (_ : r ∈ List.range 7) => by
        rw [expandS1 r,
          Finset.sum_congr rfl fun H (_ : H ∈ Finset.univ) => by
            rw [coeffS1 r H]],
      List.map_congr_left fun r (_ : r ∈ List.range 236) => by
        rw [expandS30 r,
          Finset.sum_congr rfl fun H (_ : H ∈ Finset.univ) => by
            rw [coeffS30 r H]],
      List.map_congr_left fun r (_ : r ∈ List.range 187) => by
        rw [expandS31 r,
          Finset.sum_congr rfl fun H (_ : H ∈ Finset.univ) => by
            rw [coeffS31 r H]],
      sum_list_swap', sum_list_swap', sum_list_swap',
      ← Finset.sum_add_distrib, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun H _ => ?_
    rw [map_smul_sum', map_smul_sum', map_smul_sum', ← add_smul,
      ← add_smul, listRangeSumR, listRangeSumR, listRangeSumR]
  have helt : oldRootElt = ∑ H : FlagWithSize TetraFree emptyType 7,
      (oldRootCoeff H : ℝ) •
        (⟦basisVector (⟨7, H⟩ : FinFlag TetraFree emptyType)⟧
          : FlagAlgebra TetraFree emptyType) := rfl
  rw [helt, hexp, Finset.smul_sum]
  refine Finset.sum_congr rfl fun H _ => ?_
  rw [smul_smul]
  have hsc : ((oldRootCoeff H : ℚ) : ℝ)
      = ((1 : ℝ) / 4000000000000)
        * (((1 / 140 : ℝ) * ((s1Value (boundedRep H) : ℤ) : ℚ))
          + ((1 / 1260 : ℝ) * ((s3Value (boundedRep H) : ℤ) : ℚ))) := by
    rw [show oldRootCoeff H = ((36 * s1Value (boundedRep H)
        + 4 * s3Value (boundedRep H) : ℤ) : ℚ) / columnDenom from rfl,
      show columnDenom = (20160000000000000 : ℚ) from rfl]
    push_cast
    ring
  rw [show ((oldRootCoeff H : ℚ) : ℝ) = (oldRootCoeff H : ℝ) from rfl] at hsc
  rw [hsc, add_assoc, famS1 H, famS3 H]

/-- The full coefficient identity, including the five-root families. -/
theorem isRootScaled : IsRootScaled := by
  show rootElt = ((1 : ℝ) / 4000000000000) • rootSOS
  rw [rootElt_split, oldRootElt_eq_scaled, fiveRootElt_eq_scaled]
  exact (smul_add _ oldRootSOS fiveRootSOS).symm

/-! ## The unconditional consequences -/

/-- **The order-7 semidefinite part, unconditionally.** -/
theorem rootElt_nonneg' :
    (0 : FlagAlgebra TetraFree emptyType) ≤ rootElt :=
  rootElt_nonneg isRootScaled

/-- **The full semidefinite hypothesis, unconditionally.** -/
theorem blockElt6_add_rootElt_nonneg' :
    (0 : FlagAlgebra TetraFree emptyType) ≤ blockElt6 + rootElt :=
  blockElt6_add_rootElt_nonneg isRootScaled

/-- **The bound**: a degree-stationary positive homomorphism assigns
the hyperedge at most the certificate's value. The only remaining
hypothesis of the 0.5578072552 bound is degree stationarity itself. -/
theorem edge_le_certBound_of_stationary
    (φ : PositiveHom TetraFree emptyType)
    (hφ : IsDegreeStationary φ) :
    φ edgeElt ≤ ((certBound : ℚ) : ℝ) :=
  positiveHom_edge_le_of_rootScaled φ hφ isRootScaled

/-- **Below the published record**, on the same single hypothesis. -/
theorem edge_lt_published_of_stationary
    (φ : PositiveHom TetraFree emptyType)
    (hφ : IsDegreeStationary φ) :
    φ edgeElt < (1123 / 2000 : ℝ) :=
  positiveHom_edge_lt_published_of_rootScaled φ hφ isRootScaled

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
