-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7BlockGamma.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Ext45
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Ext24

/-! # The block coefficients, computable

The rooting sums of the two extension-flag bridges, instantiated at the
certificate's factor rows and packaged as plain rational functions of
the host mask:

* for the 45-families the per-vertex weight is a stored-mask lookup
  (`w45M`), through the rigidity mask comparison;
* for the 24-family it keeps the decidable isomorphism test (`w24I`).

`fiberSum45_eq` and `fiberSum24_eq` identify the abstract fiber sums —
the coefficients `downward_linear_sq` produces — with these functions
over their normalizers. What remains after this file is numeric: the
per-class check that the certificate's `blockValue` folds compute the
same numbers, and the element-level assembly. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

open Classical

/-! ## The computable weights and sums -/

/-- The stored-mask weight: the coefficient sum of the rows whose mask
matches. -/
def w45M (flags : List ℕ) (row : List ℤ) (M : ℕ) : ℚ :=
  ∑ i ∈ Finset.range flags.length,
    ((row.getD i 0 : ℤ) : ℚ) * (if flags.getD i 0 = M then 1 else 0)

/-- The induced five-vertex mask of a four-rooting extended by an
outside vertex. -/
def indM45 (r : ℕ) (θ : Fin 4 → Fin 6) (u : Fin 6) : ℕ :=
  inducedFrom tri5 r (pack5 ![θ 0, θ 1, θ 2, θ 3, u])

/-- The rooting-and-pair sum of a 45-family row on a host mask. -/
def s45C (rm : ℕ) (flags : List ℕ) (row : List ℤ) (r : ℕ) : ℚ :=
  ∑ θ ∈ rootingsOf (rmType rm) (graphOfMask 6 r),
    ∑ p ∈ Finset.univ.filter (fun p : Fin 6 × Fin 6 =>
        p.1 ∉ Finset.univ.image θ ∧ p.2 ∉ Finset.univ.image θ
          ∧ p.1 ≠ p.2),
      w45M flags row (indM45 r θ p.1) * w45M flags row (indM45 r θ p.2)

/-- The isomorphism-test weight of the 24-family. -/
def w24I (row : List ℤ) (G : Sym3Graph 6) (θ : Fin 2 → Fin 6)
    (v w : Fin 6) : ℚ :=
  ∑ i ∈ Finset.range 11,
    ((row.getD i 0 : ℤ) : ℚ)
      * (if (blk24Flag i).IsIso (extFlag24 G θ v w) then 1 else 0)

/-- The rooting-and-pair sum of a 24-family row on a host mask. -/
def s24C (row : List ℤ) (r : ℕ) : ℚ :=
  ∑ θ ∈ rootingsOf pairType2 (graphOfMask 6 r),
    ∑ p ∈ outsidePairs θ,
      w24I row (graphOfMask 6 r) θ p.1.1 p.1.2
        * w24I row (graphOfMask 6 r) θ p.2.1 p.2.2

/-! ## The 45-family bridge to the stored masks -/

/-- The per-vertex weight is the stored-mask lookup, at any admissible
extension. -/
lemma weight45_eq_w45M (flags : List ℕ) (row : List ℤ)
    (hlt : ∀ i < flags.length, flags.getD i 0 < 2 ^ 10)
    {r : ℕ} {θ : Fin 4 → Fin 6} {u : Fin 6}
    (hθ : Function.Injective θ) (hu : u ∉ Finset.univ.image θ) :
    (∑ i : Fin flags.length, ((row.getD i.val 0 : ℤ) : ℚ)
        * (if (blk45Flag flags i.val).IsIso
            (extFlag5 (graphOfMask 6 r) θ u) then 1 else 0))
      = w45M flags row (indM45 r θ u) := by
  rw [w45M, ← Fin.sum_univ_eq_sum_range (fun k =>
    ((row.getD k 0 : ℤ) : ℚ)
      * (if flags.getD k 0 = indM45 r θ u then 1 else 0)) flags.length]
  refine Finset.sum_congr rfl fun i _ => ?_
  congr 1
  by_cases h : (blk45Flag flags i.val).IsIso (extFlag5 (graphOfMask 6 r) θ u)
  · have hm : flags.getD i.val 0 = indM45 r θ u :=
      (blk45_isIso_iff_mask hθ hu flags i.val (hlt i.val i.isLt)).mp h
    rw [if_pos h, if_pos hm]
  · have hm : ¬(flags.getD i.val 0 = indM45 r θ u) := fun hm =>
      h ((blk45_isIso_iff_mask hθ hu flags i.val
        (hlt i.val i.isLt)).mpr hm)
    rw [if_neg h, if_neg hm]

/-- **The 45-family fiber sum is the computable rooting sum** over its
normalizer `720 = 360 · 2`. -/
theorem fiberSum45_eq {rm : ℕ} [TetraFree.IsType (rmType rm).toModel]
    (flags : List ℕ) (row : List ℤ)
    (hwfF : ∀ i : Fin flags.length,
      (blk45Flag flags i.val).WellFormed (rmType rm))
    (hF : ∀ i : Fin flags.length,
      TetraFree.Mem (blk45Flag flags i.val).graph.toModel)
    (hlt : ∀ i < flags.length, flags.getD i 0 < 2 ^ 10)
    {r : ℕ} (hr : TetraFree.Mem (graphOfMask 6 r).toModel) :
    (∑ X ∈ Finset.univ.filter
        (fun X : FlagWithSize TetraFree (rmType rm).toModel 6 =>
          Flag.unlabel X = (graphOfMask 6 r).toFlag hr),
      (∑ i : Fin flags.length, ∑ j : Fin flags.length,
          ((row.getD i.val 0 : ℤ) : ℝ) * ((row.getD j.val 0 : ℤ) : ℝ)
            * ((subflagPairDensity
                ((blk45Flag flags i.val).toFlag (hwfF i) (hF i))
                ((blk45Flag flags j.val).toFlag (hwfF j) (hF j))
                X : ℚ) : ℝ))
        * (labelingFactor (Quotient.out X).unlabel (Quotient.out X) : ℝ))
      = ((s45C rm flags row r / 720 : ℚ) : ℝ) := by
  have hcast : ∀ i : Fin flags.length,
      ((row.getD i.val 0 : ℤ) : ℝ) = (((row.getD i.val 0 : ℤ) : ℚ) : ℝ) :=
    fun i => by push_cast; rfl
  rw [Finset.sum_congr rfl fun X _ => by
    rw [Finset.sum_congr rfl fun i (_ : i ∈ Finset.univ) =>
      Finset.sum_congr rfl fun j (_ : j ∈ Finset.univ) => by
        rw [hcast i, hcast j]]]
  rw [gamma45_eq_rooting (rm := rm) (fun i : Fin flags.length =>
      ((row.getD i.val 0 : ℤ) : ℚ))
    (fun i => blk45Flag flags i.val) hwfF hF hr]
  rw [show (∑ θ ∈ rootingsOf (rmType rm) (graphOfMask 6 r),
      ((((∑ p ∈ Finset.univ.filter (fun p : Fin 6 × Fin 6 =>
          p.1 ∉ Finset.univ.image θ ∧ p.2 ∉ Finset.univ.image θ
            ∧ p.1 ≠ p.2),
          (∑ i : Fin flags.length, ((row.getD i.val 0 : ℤ) : ℚ)
              * (if (blk45Flag flags i.val).IsIso
                  (extFlag5 (graphOfMask 6 r) θ p.1) then 1 else 0))
            * (∑ j : Fin flags.length, ((row.getD j.val 0 : ℤ) : ℚ)
                * (if (blk45Flag flags j.val).IsIso
                    (extFlag5 (graphOfMask 6 r) θ p.2)
                  then 1 else 0))) / 2 : ℚ)) : ℝ))
      = ∑ θ ∈ rootingsOf (rmType rm) (graphOfMask 6 r),
          ((((∑ p ∈ Finset.univ.filter (fun p : Fin 6 × Fin 6 =>
              p.1 ∉ Finset.univ.image θ ∧ p.2 ∉ Finset.univ.image θ
                ∧ p.1 ≠ p.2),
              w45M flags row (indM45 r θ p.1)
                * w45M flags row (indM45 r θ p.2)) / 2 : ℚ)) : ℝ) from by
    refine Finset.sum_congr rfl fun θ hθmem => ?_
    have hθinj : Function.Injective θ :=
      (mem_rootingsOf.mp hθmem).1
    congr 2
    refine Finset.sum_congr rfl fun p hp => ?_
    obtain ⟨-, hp1, hp2, -⟩ := Finset.mem_filter.mp hp
    rw [weight45_eq_w45M flags row hlt hθinj hp1,
      weight45_eq_w45M flags row hlt hθinj hp2]]
  rw [s45C]
  push_cast
  rw [Finset.mul_sum, Finset.sum_div]
  refine Finset.sum_congr rfl fun θ _ => ?_
  ring

/-! ## The 24-family bridge -/

/-- **The 24-family fiber sum is the computable rooting sum** over its
normalizer `180 = 30 · 6`. -/
theorem fiberSum24_eq (row : List ℤ)
    (hwfF : ∀ i : Fin 11, (blk24Flag i.val).WellFormed pairType2)
    (hF : ∀ i : Fin 11,
      TetraFree.Mem (blk24Flag i.val).graph.toModel)
    {r : ℕ} (hr : TetraFree.Mem (graphOfMask 6 r).toModel) :
    (∑ X ∈ Finset.univ.filter
        (fun X : FlagWithSize TetraFree pairType2.toModel 6 =>
          Flag.unlabel X = (graphOfMask 6 r).toFlag hr),
      (∑ i : Fin 11, ∑ j : Fin 11,
          ((row.getD i.val 0 : ℤ) : ℝ) * ((row.getD j.val 0 : ℤ) : ℝ)
            * ((subflagPairDensity
                ((blk24Flag i.val).toFlag (hwfF i) (hF i))
                ((blk24Flag j.val).toFlag (hwfF j) (hF j))
                X : ℚ) : ℝ))
        * (labelingFactor (Quotient.out X).unlabel (Quotient.out X) : ℝ))
      = ((s24C row r / 180 : ℚ) : ℝ) := by
  have hcast : ∀ i : Fin 11,
      ((row.getD i.val 0 : ℤ) : ℝ) = (((row.getD i.val 0 : ℤ) : ℚ) : ℝ) :=
    fun i => by push_cast; rfl
  rw [Finset.sum_congr rfl fun X _ => by
    rw [Finset.sum_congr rfl fun i (_ : i ∈ Finset.univ) =>
      Finset.sum_congr rfl fun j (_ : j ∈ Finset.univ) => by
        rw [hcast i, hcast j]]]
  rw [gamma24_eq_rooting (fun i : Fin 11 =>
      ((row.getD i.val 0 : ℤ) : ℚ))
    (fun i => blk24Flag i.val) hwfF hF hr]
  rw [show (∑ θ ∈ rootingsOf pairType2 (graphOfMask 6 r),
      ((((∑ p ∈ outsidePairs θ,
          (∑ i : Fin 11, ((row.getD i.val 0 : ℤ) : ℚ)
              * (if (blk24Flag i.val).IsIso
                  (extFlag24 (graphOfMask 6 r) θ p.1.1 p.1.2)
                then 1 else 0))
            * (∑ j : Fin 11, ((row.getD j.val 0 : ℤ) : ℚ)
                * (if (blk24Flag j.val).IsIso
                    (extFlag24 (graphOfMask 6 r) θ p.2.1 p.2.2)
                  then 1 else 0))) / 6 : ℚ)) : ℝ))
      = ∑ θ ∈ rootingsOf pairType2 (graphOfMask 6 r),
          ((((∑ p ∈ outsidePairs θ,
              w24I row (graphOfMask 6 r) θ p.1.1 p.1.2
                * w24I row (graphOfMask 6 r) θ p.2.1 p.2.2)
              / 6 : ℚ)) : ℝ) from by
    refine Finset.sum_congr rfl fun θ _ => ?_
    congr 2]
  rw [s24C]
  push_cast
  rw [Finset.mul_sum, Finset.sum_div]
  refine Finset.sum_congr rfl fun θ _ => ?_
  ring

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
