-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Sweep7_13.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Check

/-! Certificate sweep block 13 of 49: representatives 260–279.

Machine-generated. Every admissible labeled seven-vertex extension of
these representatives is evaluated and compared with the certificate
bound. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

set_option maxRecDepth 100000

lemma sweepBlock_13 : sweepBlockOf 13 = true := by native_decide

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
