-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Slack.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Bound
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Covered

/-! # The certificate remainder as a nonnegative flag-algebra element

The sweep bounded the certificate column on every seven-vertex graph.
This file turns that numeric fact into the object an SOS assembly
consumes: a nonnegative element of the flag algebra supported on the
seven-vertex classes.

A flag class is an isomorphism class, and the column value was defined
on masks, so the slack of a class is read off *some* mask representative
whose column obeys the bound. Coverage supplies one for every class, and
choice picks it. The resulting `slack7` is nonnegative by construction,
which is all a decomposition needs from it; the coefficient identity
that pins which representative was chosen is the separate expansion
step. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

open Classical

/-- Every seven-vertex flag class has a mask representative whose
certificate column obeys the bound. -/
theorem exists_bounded_rep (H : FlagWithSize TetraFree emptyType 7) :
    ∃ e : ℕ, ∃ he : TetraFree.Mem (graphOfMask 7 e).toModel,
      (graphOfMask 7 e).toFlag he = H ∧ columnValue e ≤ columnBound := by
  obtain ⟨G, hG, rfl⟩ :=
    exists_sym3Graph_toFlag (fun M (hM : TetraFree.Mem M) => hM.1) H
  obtain ⟨e, hiso, hle⟩ := exists_bounded_graph G hG
  obtain ⟨i⟩ := (Sym3Graph.isIso_iff_nonempty_modelIso _ _).mp hiso
  refine ⟨e, TetraFree.mem_iso i hG, ?_, hle⟩
  exact (Sym3Graph.toFlag_eq_toFlag_iff _ hG).mpr hiso.symm

/-- The chosen mask representative of a seven-vertex class. -/
noncomputable def boundedRep (H : FlagWithSize TetraFree emptyType 7) : ℕ :=
  (exists_bounded_rep H).choose

lemma boundedRep_mem (H : FlagWithSize TetraFree emptyType 7) :
    TetraFree.Mem (graphOfMask 7 (boundedRep H)).toModel :=
  (exists_bounded_rep H).choose_spec.choose

lemma toFlag_boundedRep (H : FlagWithSize TetraFree emptyType 7)
    (h : TetraFree.Mem (graphOfMask 7 (boundedRep H)).toModel) :
    (graphOfMask 7 (boundedRep H)).toFlag h = H :=
  (exists_bounded_rep H).choose_spec.choose_spec.1

lemma columnValue_boundedRep_le (H : FlagWithSize TetraFree emptyType 7) :
    columnValue (boundedRep H) ≤ columnBound :=
  (exists_bounded_rep H).choose_spec.choose_spec.2

/-! ## The slack -/

/-- **The per-class slack of the order-7 certificate**: how far the
column of a seven-vertex class falls below the bound, over the common
denominator `5040 * certScale ^ 2`. -/
noncomputable def slack7 (H : FlagWithSize TetraFree emptyType 7) : ℝ :=
  ((columnBound - columnValue (boundedRep H) : ℤ) : ℝ) / (columnDenom : ℝ)

/-- Every slack is nonnegative: this is the whole 13,051,375-column
sweep, read as one inequality per flag class. -/
theorem slack7_nonneg (H : FlagWithSize TetraFree emptyType 7) :
    0 ≤ slack7 H := by
  refine div_nonneg ?_ (by norm_num [columnDenom])
  exact_mod_cast sub_nonneg.mpr (columnValue_boundedRep_le H)

/-- **The certificate remainder**: the slack-weighted combination of the
seven-vertex classes. -/
noncomputable def remainder7 : FlagAlgebra TetraFree emptyType :=
  ∑ H : FlagWithSize TetraFree emptyType 7,
    slack7 H • ⟦basisVector (⟨7, H⟩ : FinFlag TetraFree emptyType)⟧

/-- The remainder is nonnegative in the semantic order — the slot an SOS
decomposition needs filled. -/
theorem remainder7_nonneg :
    (0 : FlagAlgebra TetraFree emptyType) ≤ remainder7 :=
  sum_nonneg' fun H _ =>
    smul_nonneg_of_nonneg (slack7_nonneg H) (flag_nonneg _)

/-- Every positive homomorphism assigns the remainder a nonnegative
value. -/
theorem positiveHom_remainder7_nonneg (φ : PositiveHom TetraFree emptyType) :
    0 ≤ φ remainder7 := by
  have h := remainder7_nonneg φ
  rwa [sub_zero] at h

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
