-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronStatComb.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronTuran
import LeanFlagAlgebras.Core.Compute.Sym3Var

/-! # The stationarity combination as pattern counts

The variance bridge, assembled. On a literal host of size at least six,
the stationarity combination `statComb` — a priori a coefficient sum
over the 964 six-vertex classes — is exactly

  `P₀ / (C(n,3)·C(n−3,3)) − P₁ / (30·C(n,5))`,

where `P₀` counts the ordered pairs of disjoint hyperedges and `P₁` the
ordered pairs meeting in one vertex. No new sweep is needed: the
certificate side is already checked (`statNum_eq_of_mem`), both
certificate halves chain through the six-vertex classes *exactly* at
any finite size (Razborov's Lemma 2.2), and the two resulting host
quantities collapse to pattern counts by the union fibration.

Combined with `sum_degree_sq`, this expresses `statComb` through the
degree statistics: the boost argument can now read a genuinely negative
stationarity combination as a lower bound on the empirical degree
variance. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-! ## A three-subset induces an edge exactly when it is one -/

/-- The per-witness form of `edge_flagCountC`: a three-subset of the
host induces a copy of the edge pattern exactly when it is an edge. -/
lemma edge_isIso_pullback_iff {n : ℕ} (G : Sym3Graph n)
    {W : Finset (Fin n)} (hW : W.card = 3) :
    edgeGraph.IsIso (G.pullback (subsetTuple W hW)) ↔ W ∈ G.edges := by
  have h3 : ∀ e : Finset (Fin 3), e.card = 3
      → e = ({0, 1, 2} : Finset (Fin 3)) := by decide
  have himg2 : ({0, 1, 2} : Finset (Fin 3)).image (subsetTuple W hW)
      = W := by
    have hsub : ∀ i : Fin 3, subsetTuple W hW i ∈ W := subsetTuple_mem W hW
    have huniv : ({0, 1, 2} : Finset (Fin 3)) = Finset.univ := by decide
    rw [huniv]
    refine Finset.eq_of_subset_of_card_le ?_ ?_
    · intro y hy
      obtain ⟨i, -, rfl⟩ := Finset.mem_image.mp hy
      exact hsub i
    · rw [Finset.card_image_of_injective _ (subsetTuple_injective W hW),
        Finset.card_univ, Fintype.card_fin, hW]
  constructor
  · rintro ⟨p, hedges⟩
    have h1 : ({0, 1, 2} : Finset (Fin 3))
        ∈ (G.pullback (subsetTuple W hW)).edges := by
      have h0 : ({0, 1, 2} : Finset (Fin 3)).image ⇑p
          ∈ (G.pullback (subsetTuple W hW)).edges := by
        rw [← hedges]
        refine Finset.mem_image.mpr ⟨{0, 1, 2}, ?_, rfl⟩
        decide
      have himg : ({0, 1, 2} : Finset (Fin 3)).image ⇑p
          = ({0, 1, 2} : Finset (Fin 3)) :=
        h3 _ (by
          rw [Finset.card_image_of_injective _ p.injective]
          decide)
      rwa [himg] at h0
    have h2 := (Finset.mem_filter.mp (show ({0, 1, 2} : Finset (Fin 3))
        ∈ Finset.univ.filter _ from h1)).2.2
    rwa [himg2] at h2
  · intro he
    have hpull : (G.pullback (subsetTuple W hW)).edges
        = ({({0, 1, 2} : Finset (Fin 3))} : Finset (Finset (Fin 3))) := by
      ext t
      show t ∈ Finset.univ.filter _ ↔ _
      rw [Finset.mem_filter, Finset.mem_singleton]
      constructor
      · rintro ⟨-, hc, -⟩
        exact h3 t hc
      · rintro rfl
        refine ⟨Finset.mem_univ _, by decide, ?_⟩
        rw [himg2]
        exact he
    have hedge : edgeGraph.edges
        = ({({0, 1, 2} : Finset (Fin 3))} : Finset (Finset (Fin 3))) := by
      decide
    refine ⟨(1 : Equiv.Perm (Fin 3)), ?_⟩
    rw [hedge, hpull]
    ext t
    constructor
    · intro ht
      obtain ⟨t₀, ht₀, rfl⟩ := Finset.mem_image.mp ht
      rw [Finset.mem_singleton] at ht₀
      subst ht₀
      rw [Finset.mem_singleton]
      refine h3 _ ?_
      rw [Finset.card_image_of_injective _
        ((1 : Equiv.Perm (Fin 3)).injective)]
      decide
    · intro ht
      rw [Finset.mem_singleton] at ht
      subst ht
      refine Finset.mem_image.mpr
        ⟨{0, 1, 2}, Finset.mem_singleton_self _, ?_⟩
      refine h3 _ ?_
      rw [Finset.card_image_of_injective _
        ((1 : Equiv.Perm (Fin 3)).injective)]
      decide

/-! ## `P₀`: the disjoint pairs are the edge pair count -/

/-- **Disjoint edge pairs are the edge pair count**: intersection size
zero is disjointness, and a three-subset induces an edge exactly when
it is one. -/
lemma pairCountInter_zero_eq {n : ℕ} (G : Sym3Graph n) :
    G.pairCountInter 0 = edgeGraph.flagPairCountC edgeGraph G := by
  rw [Sym3Graph.pairCountInter, Sym3Graph.flagPairCountC]
  refine Finset.card_bij (fun q hq => ⟨(q.1, q.2), ?_⟩) ?_ ?_ ?_
  · have hm := Finset.mem_product.mp (Finset.mem_filter.mp hq).1
    refine Finset.mem_product.mpr
      ⟨Finset.mem_powersetCard.mpr
        ⟨Finset.subset_univ _, G.edges_valid _ hm.1⟩,
       Finset.mem_powersetCard.mpr
        ⟨Finset.subset_univ _, G.edges_valid _ hm.2⟩⟩
  · rintro ⟨e, f⟩ hq
    obtain ⟨hmem, hc⟩ := Finset.mem_filter.mp hq
    have hm := Finset.mem_product.mp hmem
    refine Finset.mem_filter.mpr ⟨Finset.mem_attach _ _, ?_, ?_, ?_⟩
    · exact Finset.disjoint_iff_inter_eq_empty.mpr
        (Finset.card_eq_zero.mp hc)
    · exact (edge_isIso_pullback_iff G _).mpr hm.1
    · exact (edge_isIso_pullback_iff G _).mpr hm.2
  · rintro ⟨e₁, f₁⟩ h₁ ⟨e₂, f₂⟩ h₂ heq
    have := congrArg Subtype.val heq
    dsimp at this
    rw [Prod.mk.injEq] at this ⊢
    exact this
  · rintro ⟨⟨W₁, W₂⟩, hP⟩ hmem
    obtain ⟨-, hdisj, hiso₁, hiso₂⟩ := Finset.mem_filter.mp hmem
    have he₁ : W₁ ∈ G.edges := (edge_isIso_pullback_iff G _).mp hiso₁
    have he₂ : W₂ ∈ G.edges := (edge_isIso_pullback_iff G _).mp hiso₂
    refine ⟨(W₁, W₂), Finset.mem_filter.mpr
      ⟨Finset.mem_product.mpr ⟨he₁, he₂⟩, ?_⟩, ?_⟩
    · show (W₁ ∩ W₂).card = 0
      rw [Finset.disjoint_iff_inter_eq_empty.mp hdisj]
      exact Finset.card_empty
    · exact Subtype.ext rfl

/-! ## `P₁`: the five-vertex coefficients are local pair counts -/

/-- The rooting-averaged pair count of a listed K4-free five-vertex
representative is its local `1`-intersecting pair count over `30`: one
rational check per class. -/
lemma gamma5C_check :
    (((sym3Reps 5).filter fun H => decide (TetraFree.Mem H.toModel)).all
      fun H => decide (gamma5C H
        = (H.pairCountInter 1 : ℚ) / 30)) = true := by
  native_decide

lemma gamma5C_eq_of_mem {H : Sym3Graph 5}
    (hH : H ∈ (sym3Reps 5).filter
      fun H => decide (TetraFree.Mem H.toModel)) :
    gamma5C H = (H.pairCountInter 1 : ℚ) / 30 := by
  have := List.all_eq_true.mp gamma5C_check H hH
  simpa using this

/-! ## List-sum bookkeeping -/

private lemma pmap_sum_eq {α β : Type} [AddCommMonoid β] {p : α → Prop}
    (f : (a : α) → p a → β) (c : α → β)
    (hfc : ∀ a ha, f a ha = c a) :
    ∀ (l : List α) (H : ∀ a ∈ l, p a),
      (l.pmap f H).sum = (l.map c).sum := by
  intro l
  induction l with
  | nil => intro H; rfl
  | cons a t ih =>
    intro H
    rw [List.pmap, List.map, List.sum_cons, List.sum_cons, hfc, ih]

private lemma cast_list_sum :
    ∀ l : List ℚ, ((l.sum : ℚ) : ℝ)
      = (l.map fun q : ℚ => (q : ℝ)).sum := by
  intro l
  induction l with
  | nil => simp
  | cons a t ih =>
    rw [List.map, List.sum_cons, List.sum_cons, Rat.cast_add, ih]

private lemma list_sum_map_div {α : Type} (g : α → ℕ) (d : ℚ) :
    ∀ L : List α,
      (L.map fun a => ((g a : ℚ)) / d).sum
        = (((L.map g).sum : ℕ) : ℚ) / d := by
  intro L
  induction L with
  | nil => simp
  | cons a l ih =>
    rw [List.map_cons, List.sum_cons, ih, List.map_cons, List.sum_cons]
    push_cast
    ring

/-! ## The five-vertex average collapses to `P₁` -/

/-- The five-vertex class average on a literal host, transported to the
representative listing — `statSum_eq` at an arbitrary size. -/
lemma statSum_eq_host {n : ℕ} (G : Sym3Graph n)
    (hG : TetraFree.Mem G.toModel) :
    (∑ H₅ : FlagWithSize TetraFree emptyType 5,
        degGamma5 H₅ * ((subflagDensity H₅ (G.toFlag hG) : ℚ) : ℝ))
      = (((((sym3Reps 5).filter fun H =>
            decide (TetraFree.Mem H.toModel)).map
          fun H₅ => gamma5C H₅
            * ((H₅.flagCountC G : ℚ) / (n.choose 5 : ℚ))).sum : ℚ) : ℝ) := by
  rw [sum_flag_eq_sum_sym3FlagReps TetraFree
    (fun M (hM : TetraFree.Mem M) => hM.1)
    (fun H₅ => degGamma5 H₅
      * ((subflagDensity H₅ (G.toFlag hG) : ℚ) : ℝ)),
    sym3FlagReps, List.map_pmap]
  rw [pmap_sum_eq _
    (fun H₅ => ((gamma5C H₅
      * ((H₅.flagCountC G : ℚ) / (n.choose 5 : ℚ)) : ℚ) : ℝ)) ?_ _ _]
  · rw [cast_list_sum, List.map_map]
    rfl
  · intro H₅ hH₅
    rw [degGamma5_eq_gamma5C hH₅,
      Sym3Graph.subflagDensity_toFlag hH₅ hG]
    push_cast
    ring

/-- **The five-vertex average is the `P₁` count over its normalizer**:
each listed coefficient is the local pair count over `30`, and the
representative sum collapses by the union fibration. -/
lemma statSum_eq_pairCount {n : ℕ} (G : Sym3Graph n)
    (hG : TetraFree.Mem G.toModel) :
    (∑ H₅ : FlagWithSize TetraFree emptyType 5,
        degGamma5 H₅ * ((subflagDensity H₅ (G.toFlag hG) : ℚ) : ℝ))
      = (((G.pairCountInter 1 : ℚ) / (30 * (n.choose 5 : ℚ)) : ℚ) : ℝ) := by
  rw [statSum_eq_host G hG]
  have hterm : ∀ H₅ ∈ (sym3Reps 5).filter
      fun H => decide (TetraFree.Mem H.toModel),
      gamma5C H₅ * ((H₅.flagCountC G : ℚ) / (n.choose 5 : ℚ))
        = ((H₅.pairCountInter 1 * H₅.flagCountC G : ℕ) : ℚ)
            / (30 * (n.choose 5 : ℚ)) := by
    intro H₅ hH₅
    rw [gamma5C_eq_of_mem hH₅]
    push_cast
    ring
  rw [List.map_congr_left hterm,
    list_sum_map_div
      (fun H₅ : Sym3Graph 5 => H₅.pairCountInter 1 * H₅.flagCountC G)
      (30 * (n.choose 5 : ℚ)),
    Sym3Graph.sum_reps_pairCountInter G hG (by norm_num : 1 + 5 = 6)]

/-! ## The stationarity combination as the explicit class sum -/

/-- The explicit stationarity vector's coefficient at a six-vertex
class: `statNum/180`. -/
lemma statVec_apply (H : FlagWithSize TetraFree emptyType 6) :
    statVec ⟨6, H⟩ = ((statNumOf H / 180 : ℚ) : ℝ) := by
  rw [statVec, Finsupp.smul_apply, Finsupp.finset_sum_apply]
  have hother : ∀ H' : FlagWithSize TetraFree emptyType 6,
      H' ∈ (Finset.univ : Finset (FlagWithSize TetraFree emptyType 6)) →
      H' ≠ H →
      (((statNumOf H' / 60 : ℚ) : ℝ) • basisVector
        (⟨6, H'⟩ : FinFlag TetraFree emptyType)) ⟨6, H⟩ = 0 := by
    intro H' _ hne
    have hne' : (⟨6, H'⟩ : FinFlag TetraFree emptyType) ≠ ⟨6, H⟩ :=
      fun heq => hne (by simpa using heq)
    rw [Finsupp.smul_apply, basisVector_apply_other _ _ hne', smul_zero]
  rw [Finset.sum_eq_single H hother
      (fun h => absurd (Finset.mem_univ H) h),
    Finsupp.smul_apply, basisVector_apply_self]
  simp only [smul_eq_mul, mul_one]
  push_cast
  ring

/-- The stationarity combination is the coefficient sum over all
six-vertex classes. -/
lemma statComb_eq_sum6 {n : ℕ} (G : FlagWithSize TetraFree emptyType n) :
    statComb ⟨n, G⟩
      = ∑ H : FlagWithSize TetraFree emptyType 6,
          ((statNumOf H / 180 : ℚ) : ℝ)
            * ((subflagDensity H G : ℚ) : ℝ) := by
  classical
  show ∑ F ∈ statVec.support,
      statVec F * ((subflagDensity F.2 G : ℚ) : ℝ) = _
  have hsub : statVec.support ⊆
      (Finset.univ : Finset (FlagWithSize TetraFree emptyType 6)).image
        (fun H => (⟨6, H⟩ : FinFlag TetraFree emptyType)) := by
    intro F hF
    by_contra hFim
    refine Finsupp.mem_support_iff.mp hF ?_
    rw [statVec, Finsupp.smul_apply, Finsupp.finset_sum_apply]
    have h0 : ∀ H ∈ (Finset.univ :
        Finset (FlagWithSize TetraFree emptyType 6)),
        (((statNumOf H / 60 : ℚ) : ℝ) • basisVector
          (⟨6, H⟩ : FinFlag TetraFree emptyType)) F = 0 := by
      intro H _
      have hne : (⟨6, H⟩ : FinFlag TetraFree emptyType) ≠ F :=
        fun heq => hFim (Finset.mem_image.mpr ⟨H, Finset.mem_univ H, heq⟩)
      rw [Finsupp.smul_apply, basisVector_apply_other _ _ hne, smul_zero]
    rw [Finset.sum_eq_zero h0, smul_zero]
  rw [Finset.sum_subset hsub (fun F _ hF => by
      have h0 : statVec F = 0 := by
        by_contra h
        exact hF (Finsupp.mem_support_iff.mpr h)
      rw [h0, zero_mul]),
    Finset.sum_image (fun H _ H' _ heq => by
      injection heq with h1 h2)]
  exact Finset.sum_congr rfl fun H _ => by rw [statVec_apply]

/-! ## The coefficient identity, and the chain rules -/

/-- The six-vertex coefficient, read off the certificate check: the
stationarity numerator over `180` is the edge pair density minus the
five-vertex average. -/
lemma statNum_coeff_eq (H : FlagWithSize TetraFree emptyType 6) :
    ((statNumOf H / 180 : ℚ) : ℝ)
      = ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
            (edgeGraph.toFlag edgeGraph_mem) H : ℚ) : ℝ)
        - ∑ H₅ : FlagWithSize TetraFree emptyType 5,
            degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ) := by
  have hcoeff : ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
        (edgeGraph.toFlag edgeGraph_mem) H : ℚ) : ℝ)
      - ∑ H₅ : FlagWithSize TetraFree emptyType 5,
          degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ)
      = ((statCoeffC (graphOfMask 6 (repMask H)) : ℚ) : ℝ) := by
    conv_lhs => rw [← toFlag_repMask H (repMask_memT H)]
    exact stationarity_coeff_eq (graphOfMask 6 (repMask H)) (repMask_memT H)
  rw [hcoeff]
  have hnum : (statNumOf H / 180 : ℚ)
      = statCoeffC (graphOfMask 6 (repMask H)) := by
    have h1 : statNumOf H = statNum (repMask H) := rfl
    have h2 := statNum_eq_of_mem (repMask_mem H)
    rw [h1, h2]
    ring
  exact_mod_cast hnum

/-- **The stationarity combination chains to the host** (Razborov's
Lemma 2.2): on any flag of size at least six, `statComb` is exactly the
edge pair density minus the five-vertex average, evaluated directly on
the host — the identity is exact at every finite size, not just in the
limit. -/
theorem statComb_eq_host {n : ℕ} (G : FlagWithSize TetraFree emptyType n)
    (hn : 6 ≤ n) :
    statComb ⟨n, G⟩
      = ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
            (edgeGraph.toFlag edgeGraph_mem) G : ℚ) : ℝ)
        - ∑ H₅ : FlagWithSize TetraFree emptyType 5,
            degGamma5 H₅ * ((subflagDensity H₅ G : ℚ) : ℝ) := by
  have hCR1 : ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
        (edgeGraph.toFlag edgeGraph_mem) G : ℚ) : ℝ)
      = ∑ H : FlagWithSize TetraFree emptyType 6,
          ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
              (edgeGraph.toFlag edgeGraph_mem) H : ℚ) : ℝ)
            * ((subflagDensity H G : ℚ) : ℝ) := by
    rw [subflagPairDensity_chain_host (W' := Fin 6) (by simp)
      (by simpa using hn) (edgeGraph.toFlag edgeGraph_mem)
      (edgeGraph.toFlag edgeGraph_mem) G]
    push_cast
    rfl
  have hCR2 : ∀ H₅ : FlagWithSize TetraFree emptyType 5,
      ((subflagDensity H₅ G : ℚ) : ℝ)
        = ∑ H : FlagWithSize TetraFree emptyType 6,
            ((subflagDensity H₅ H : ℚ) : ℝ)
              * ((subflagDensity H G : ℚ) : ℝ) := by
    intro H₅
    rw [subflagDensity_chain (W' := Fin 6) (by simp)
      (by simpa using hn) H₅ G]
    push_cast
    rfl
  have hsubst : ∑ H : FlagWithSize TetraFree emptyType 6,
      ((statNumOf H / 180 : ℚ) : ℝ) * ((subflagDensity H G : ℚ) : ℝ)
      = ∑ H : FlagWithSize TetraFree emptyType 6,
          (((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
                (edgeGraph.toFlag edgeGraph_mem) H : ℚ) : ℝ)
              * ((subflagDensity H G : ℚ) : ℝ)
            - (∑ H₅ : FlagWithSize TetraFree emptyType 5,
                degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ))
              * ((subflagDensity H G : ℚ) : ℝ)) :=
    Finset.sum_congr rfl fun H _ => by
      rw [statNum_coeff_eq H, sub_mul]
  have hswap : ∑ H : FlagWithSize TetraFree emptyType 6,
      (∑ H₅ : FlagWithSize TetraFree emptyType 5,
        degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ))
        * ((subflagDensity H G : ℚ) : ℝ)
      = ∑ H₅ : FlagWithSize TetraFree emptyType 5,
          degGamma5 H₅ * ((subflagDensity H₅ G : ℚ) : ℝ) := by
    have h1 : ∀ H : FlagWithSize TetraFree emptyType 6,
        (∑ H₅ : FlagWithSize TetraFree emptyType 5,
          degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ))
          * ((subflagDensity H G : ℚ) : ℝ)
        = ∑ H₅ : FlagWithSize TetraFree emptyType 5,
            degGamma5 H₅ * (((subflagDensity H₅ H : ℚ) : ℝ)
              * ((subflagDensity H G : ℚ) : ℝ)) := by
      intro H
      rw [Finset.sum_mul]
      exact Finset.sum_congr rfl fun H₅ _ => by ring
    rw [Finset.sum_congr rfl fun H _ => h1 H, Finset.sum_comm]
    refine Finset.sum_congr rfl fun H₅ _ => ?_
    rw [← Finset.mul_sum, ← hCR2 H₅]
  rw [statComb_eq_sum6 G, hsubst, Finset.sum_sub_distrib, ← hCR1, hswap]

/-- **The stationarity combination as pattern counts**: on a literal
tetrahedron-free host of size at least six,

  `statComb = P₀ / (C(n,3)·C(n-3,3)) − P₁ / (30·C(n,5))`,

where `P₀` counts ordered pairs of disjoint hyperedges and `P₁` ordered
pairs meeting in one vertex. Together with `sum_degree_sq` this reads
the stationarity combination as an empirical degree statistic — the
finite input of the boost argument. -/
theorem statComb_toFlag_eq {n : ℕ} (G : Sym3Graph n)
    (hG : TetraFree.Mem G.toModel) (hn : 6 ≤ n) :
    statComb ⟨n, G.toFlag hG⟩
      = (G.pairCountInter 0 : ℝ) / (pairChoose n 3 3 : ℝ)
        - (G.pairCountInter 1 : ℝ) / (30 * (n.choose 5 : ℝ)) := by
  rw [statComb_eq_host (G.toFlag hG) hn, statSum_eq_pairCount G hG,
    Sym3Graph.subflagPairDensity_toFlag edgeGraph_mem edgeGraph_mem hG,
    ← pairCountInter_zero_eq]
  push_cast
  ring

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
