-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Sweep7_17.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Check

/-! Certificate sweep block 17 of 49: representatives 340–359.

Machine-generated. Every admissible labeled seven-vertex extension of
these representatives is evaluated and compared with the certificate
bound. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

set_option maxRecDepth 100000

lemma sweepBlock_17 : sweepBlockOf 17 = true := by native_decide

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
