import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors00
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors01
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors02
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors03
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors04
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors05
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors06
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors07
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors08
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors09
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors10
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors11
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors12
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors13
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors14
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors15
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors16
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7FiveRootFactors17
import LeanFlagAlgebras.Core.Compute.Mask3

-- Generated by scripts/exact_certificate/derive_full_seven_long_five_root.py.
namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-- Integer square-factor data, with every labeled six-vertex flag retained. -/
structure FiveRootData where
  sigma : ℕ
  dimension : ℕ
  rows : ℕ
  flags : Array ℕ
  links : Array ℕ
  linkIndex : Array ℕ
  factors : Array ℤ
  autos : Array ℕ
  action : Array ℕ
  deriving Inhabited

def s5Data : Array FiveRootData := #[
  ⟨0, 1024, 20, s5Flags00, s5Links00, s5LinkIndex00, s5Factors00, s5Autos00, s5Action00⟩,
  ⟨1, 896, 27, s5Flags01, s5Links01, s5LinkIndex01, s5Factors01, s5Autos01, s5Action01⟩,
  ⟨3, 800, 37, s5Flags02, s5Links02, s5LinkIndex02, s5Factors02, s5Autos02, s5Action02⟩,
  ⟨7, 728, 16, s5Flags03, s5Links03, s5LinkIndex03, s5Factors03, s5Autos03, s5Action03⟩,
  ⟨11, 720, 23, s5Flags04, s5Links04, s5LinkIndex04, s5Factors04, s5Autos04, s5Action04⟩,
  ⟨15, 652, 25, s5Flags05, s5Links05, s5LinkIndex05, s5Factors05, s5Autos05, s5Action05⟩,
  ⟨30, 644, 36, s5Flags06, s5Links06, s5LinkIndex06, s5Factors06, s5Autos06, s5Action06⟩,
  ⟨31, 594, 39, s5Flags07, s5Links07, s5LinkIndex07, s5Factors07, s5Autos07, s5Action07⟩,
  ⟨63, 545, 2, s5Flags08, s5Links08, s5LinkIndex08, s5Factors08, s5Autos08, s5Action08⟩,
  ⟨77, 640, 1, s5Flags09, s5Links09, s5LinkIndex09, s5Factors09, s5Autos09, s5Action09⟩,
  ⟨87, 584, 6, s5Flags10, s5Links10, s5LinkIndex10, s5Factors10, s5Autos10, s5Action10⟩,
  ⟨94, 578, 29, s5Flags11, s5Links11, s5LinkIndex11, s5Factors11, s5Autos11, s5Action11⟩,
  ⟨116, 637, 14, s5Flags12, s5Links12, s5LinkIndex12, s5Factors12, s5Autos12, s5Action12⟩,
  ⟨117, 580, 18, s5Flags13, s5Links13, s5LinkIndex13, s5Factors13, s5Autos13, s5Action13⟩,
  ⟨119, 532, 31, s5Flags14, s5Links14, s5LinkIndex14, s5Factors14, s5Autos14, s5Action14⟩,
  ⟨222, 526, 10, s5Flags15, s5Links15, s5LinkIndex15, s5Factors15, s5Autos15, s5Action15⟩,
  ⟨237, 527, 18, s5Flags16, s5Links16, s5LinkIndex16, s5Factors16, s5Autos16, s5Action16⟩,
  ⟨254, 483, 8, s5Flags17, s5Links17, s5LinkIndex17, s5Factors17, s5Autos17, s5Action17⟩]

def s5Block (b : Fin 18) : FiveRootData := s5Data.getD b.val default
def s5Dim (b : Fin 18) : ℕ := (s5Block b).dimension
def s5Rows (b : Fin 18) : ℕ := (s5Block b).rows
def s5Type (b : Fin 18) : Sym3Graph 5 := graphOfMask 5 (s5Block b).sigma
def s5FlagMask (b : Fin 18) (i : ℕ) : ℕ := (s5Block b).flags.getD i 0
def s5Flag (b : Fin 18) (i : ℕ) : Sym3Flag 5 6 :=
  ⟨graphOfMask 6 (s5FlagMask b i), ![0, 1, 2, 3, 4]⟩
def fS5 (b : Fin 18) (r i : ℕ) : ℤ :=
  (s5Block b).factors.getD (r * s5Dim b + i) 0

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
