-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Fiber.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7ClassIdx

/-! # The deck sum as a level-6 expansion

The chain rule says a six-vertex class occupies a fraction of the seven
decks equal to its density. Grouping the seven decks by class turns any
sum over decks into a density-weighted sum over classes — which is the
shape a flag-algebra expansion has.

So whatever quantity the certificate attaches to a six-vertex class, its
deck sum is seven times the level-7 coefficient of the order-6 element
carrying that quantity. The factor of seven is the same one the
certificate's denominators carry: `5040 = 7 * 720`. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

open Classical

/-- The six-vertex flag class of the deck that deletes `v`. -/
def deckClass {m : ℕ} (hk4 : k4FreeMask (quadIdxList 7) m = true) (v : Fin 7) :
    FlagWithSize TetraFree emptyType 6 :=
  (graphOfMask 6 (deckMask v m)).toFlag
    (k4FreeMask_iff_mem.mp (deckMask_k4Free v hk4))

/-- The chain rule with the class named abstractly: the density of a
six-vertex class is the fraction of decks lying in it. -/
theorem subflagDensity_deckClass {m : ℕ}
    (hk4 : k4FreeMask (quadIdxList 7) m = true)
    (hm : TetraFree.Mem (graphOfMask 7 m).toModel)
    (H : FlagWithSize TetraFree emptyType 6) :
    subflagDensity H ((graphOfMask 7 m).toFlag hm)
      = ((Finset.univ.filter fun v : Fin 7 =>
          deckClass hk4 v = H).card : ℚ) / 7 := by
  obtain ⟨G, hG, rfl⟩ :=
    exists_sym3Graph_toFlag (fun M (hM : TetraFree.Mem M) => hM.1) H
  have hfil : (Finset.univ.filter fun v : Fin 7 =>
        deckClass hk4 v = G.toFlag hG)
      = Finset.univ.filter fun v : Fin 7 =>
        G.IsIso (graphOfMask 6 (deckMask v m)) := by
    refine Finset.filter_congr fun v _ => ?_
    rw [deckClass, Sym3Graph.toFlag_eq_toFlag_iff]
    exact ⟨isIso_symm, isIso_symm⟩
  rw [subflagDensity_deck hG hm, hfil]

/-- **The deck sum is a level-6 expansion**: summing any quantity over
the seven decks gives seven times its density-weighted sum over the
six-vertex classes. -/
theorem sum_deckClass (f : FlagWithSize TetraFree emptyType 6 → ℚ) {m : ℕ}
    (hk4 : k4FreeMask (quadIdxList 7) m = true)
    (hm : TetraFree.Mem (graphOfMask 7 m).toModel) :
    ∑ v : Fin 7, f (deckClass hk4 v)
      = 7 * ∑ H : FlagWithSize TetraFree emptyType 6,
          f H * subflagDensity H ((graphOfMask 7 m).toFlag hm) := by
  classical
  rw [Finset.mul_sum]
  rw [← Finset.sum_fiberwise Finset.univ (fun v : Fin 7 => deckClass hk4 v)
    (fun v => f (deckClass hk4 v))]
  refine Finset.sum_congr rfl fun H _ => ?_
  rw [subflagDensity_deckClass hk4 hm H]
  rw [Finset.sum_congr rfl (g := fun _ => f H) fun v hv => by
    rw [(Finset.mem_filter.mp hv).2]]
  rw [Finset.sum_const, nsmul_eq_mul]
  ring

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
