-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronOrder7Realize.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.TetrahedronOrder7Distinct
import LeanFlagAlgebras.Core.Compute.Relabel6
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Edges

/-! # Realization: every seven-vertex graph is in the enumeration

The sweep checks extensions of the listed six-vertex representatives.
This file closes the gap to arbitrary graphs: every tetrahedron-free
seven-vertex mask is isomorphic to one of those extensions.

The argument is the expected one. Delete the last vertex; the rest is a
tetrahedron-free six-vertex graph, so the classification matches it with
a listed representative, and the converse bridge turns that match into
one of the tabulated permutations together with a correspondence of bits.
Extending the permutation by fixing the last vertex, and transporting the
link along it, produces the extension; the two shapes of sorted triple
are handled by the relabelling lemmas.

Every step is kept in its own declaration. Elaboration budget is counted
per declaration, and instantiating the certificate tables is expensive
enough here that one long proof runs out. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

/-- The bit correspondence a passing scan carries, at level six. -/
private lemma bits6_of_scan {m h i : ℕ} (hi : i < 720)
    (hscan : scanOK m (getRank i) h = true) :
    ∀ a b c : Fin 6, a < b → b < c →
      m.testBit (triIdx 6 a.val b.val c.val)
        = h.testBit (triIdx 6
            (sort3 (permFn (getPerm i) a) (permFn (getPerm i) b)
              (permFn (getPerm i) c)).1.val
            (sort3 (permFn (getPerm i) a) (permFn (getPerm i) b)
              (permFn (getPerm i) c)).2.1.val
            (sort3 (permFn (getPerm i) a) (permFn (getPerm i) b)
              (permFn (getPerm i) c)).2.2.val) := by
  have hcons := permConsistent_of_lt hi
  unfold permConsistent at hcons
  rw [Bool.and_eq_true] at hcons
  have hmap := of_decide_eq_true hcons.2
  have hscan' := List.all_eq_true.mp hscan
  intro a b c hab hbc
  have hs := hscan' _ (List.mem_range.mpr (triIdx6_lt a b c hab hbc))
  simp only [beq_iff_eq] at hs
  rw [hs, hmap a b c hab hbc]

/-- The relabelled correspondence, for a triple avoiding the last
vertex. -/
private lemma ext_bits_lt {m h i link : ℕ} (hi : i < 720)
    (hscan : scanOK (deck6 m) (getRank i) h = true)
    {a b c : Fin 7} (hab : a < b) (hbc : b < c) (hc : c.val < 6) :
    m.testBit (triIdx 7 a.val b.val c.val)
      = (extendMask h link).testBit (triIdx 7
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).1.val
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).2.1.val
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).2.2.val) := by
  have ha : a.val < 6 := by omega
  have hb : b.val < 6 := by omega
  obtain ⟨a', rfl⟩ : ∃ a' : Fin 6, a = embed6 a' := ⟨⟨a.val, ha⟩, Fin.ext rfl⟩
  obtain ⟨b', rfl⟩ : ∃ b' : Fin 6, b = embed6 b' := ⟨⟨b.val, hb⟩, Fin.ext rfl⟩
  obtain ⟨c', rfl⟩ : ∃ c' : Fin 6, c = embed6 c' := ⟨⟨c.val, hc⟩, Fin.ext rfl⟩
  obtain ⟨hsort, hs1, hs2⟩ :=
    relabel_sort_lt (permFn_injective_of_lt hi) (hab : a' < b') (hbc : b' < c')
  rw [hsort, extendMask_testBit_lt (embed6_lt hs1) (embed6_lt hs2)
      (embed6_lt_six _), ← deck6_testBit hab hbc hc]
  simp only [embed6_val]
  exact bits6_of_scan hi hscan a' b' c' hab hbc

/-- The relabelled correspondence, for a triple through the last
vertex. -/
private lemma ext_bits_last {m h i : ℕ} (hi : i < 720)
    {a b c : Fin 7} (hab : a < b) (hb : b.val < 6) (hc : c.val = 6) :
    m.testBit (triIdx 7 a.val b.val c.val)
      = (extendMask h (pullLink (permFn (getPerm i)) m)).testBit (triIdx 7
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).1.val
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).2.1.val
          (sort3 (extendFn (permFn (getPerm i)) a)
            (extendFn (permFn (getPerm i)) b)
            (extendFn (permFn (getPerm i)) c)).2.2.val) := by
  have ha : a.val < 6 := by omega
  obtain ⟨a', rfl⟩ : ∃ a' : Fin 6, a = embed6 a' := ⟨⟨a.val, ha⟩, Fin.ext rfl⟩
  obtain ⟨b', rfl⟩ : ∃ b' : Fin 6, b = embed6 b' := ⟨⟨b.val, hb⟩, Fin.ext rfl⟩
  obtain ⟨hsort, hmm⟩ :=
    relabel_sort_last (permFn_injective_of_lt hi) (hab : a' < b') hc
  rw [hsort, show ((⟨6, by omega⟩ : Fin 7) : ℕ) = 6 from rfl,
    extendMask_testBit_last (embed6_lt hmm) (embed6_lt_six _)]
  simp only [embed6_val, hc]
  exact (pullLink_testBit_img (permFn_injective_of_lt hi) m hab).symm

/-- **Realization**: every tetrahedron-free seven-vertex mask is
isomorphic to an extension of a listed representative. -/
theorem exists_extension_isIso {m : ℕ} (hk4 : k4FreeMask (quadIdxList 7) m = true) :
    ∃ h ∈ h6Reps, ∃ link < 32768,
      (graphOfMask 7 m).IsIso (graphOfMask 7 (extendMask h link)) := by
  obtain ⟨h, hhmem, hiso⟩ := h6Reps_complete (deck6_lt m) (deck6_k4Free hk4)
  obtain ⟨i, hi, hscan⟩ := exists_scan_of_isIso hiso
  refine ⟨h, hhmem, pullLink (permFn (getPerm i)) m,
    pullLink_lt (permFn_injective_of_lt hi) m, ?_⟩
  refine isIso_graphOfMask_of_bits
    (extendFn_injective (permFn_injective_of_lt hi)) ?_
  intro a b c hab hbc
  by_cases hc : c.val < 6
  · exact ext_bits_lt hi hscan hab hbc hc
  · exact ext_bits_last hi hab (by omega) (by omega)

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
