-- Generated by scripts/exact_certificate/derive_full_seven_long_chain.py.
-- The certificate and all source hashes are recorded in this directory's manifest.json.
-- Proof template: scripts/exact_certificate/templates/Examples/TetrahedronDegreeCheck.lean; certificate-dependent imports redirected.
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronDegreeExpand
import LeanFlagAlgebras.Core.Examples.FullSevenLong.TetrahedronOrder7Pieces

/-! # The stationarity coefficient, fully computable

The six-vertex coefficient of the degree stationarity element is an
edge pair density minus an average over the five-vertex classes. Both
halves reduce to counts: the pair density is a pair count over twenty,
and the five-vertex sum transports to the canonical representative
listing, where each class contributes its computable `gamma5C` times a
subflag count over six.

`statCoeffC` is that rational, and `stationarity_coeff_eq` identifies
it with the abstract coefficient on every literal host. What remains
for `statElt6 = degreeStationarity` is the per-class check
`statNum h / 60 = statCoeffC (graphOfMask 6 h)` on the 964
representatives. -/

namespace FlagAlgebras.Core.Tetrahedron.FullSevenLong

open FlagAlgebras.Core

open Classical

/-! ## List-sum bookkeeping -/

private lemma pmap_sum_eq {α β : Type} [AddCommMonoid β] {p : α → Prop}
    (f : (a : α) → p a → β) (c : α → β)
    (hfc : ∀ a ha, f a ha = c a) :
    ∀ (l : List α) (H : ∀ a ∈ l, p a), (l.pmap f H).sum = (l.map c).sum := by
  intro l
  induction l with
  | nil => intro H; rfl
  | cons a t ih =>
    intro H
    rw [List.pmap, List.map, List.sum_cons, List.sum_cons, hfc, ih]

private lemma cast_list_sum :
    ∀ l : List ℚ, ((l.sum : ℚ) : ℝ) = (l.map fun q : ℚ => (q : ℝ)).sum := by
  intro l
  induction l with
  | nil => simp
  | cons a t ih => rw [List.map, List.sum_cons, List.sum_cons, Rat.cast_add, ih]

/-! ## The computable coefficient -/

/-- **The stationarity coefficient of a six-vertex host**: the edge pair
count over twenty, minus each five-vertex class's rooting-averaged pair
count times its subflag count over six. -/
def statCoeffC (G₆ : Sym3Graph 6) : ℚ :=
  (edgeGraph.flagPairCountC edgeGraph G₆ : ℚ) / 20
    - (((sym3Reps 5).filter fun G => decide (TetraFree.Mem G.toModel)).map
        fun G₅ => gamma5C G₅ * ((G₅.flagCountC G₆ : ℚ) / 6)).sum

/-- The five-vertex average, transported to the representative
listing. -/
lemma statSum_eq (G₆ : Sym3Graph 6) (hG₆ : TetraFree.Mem G₆.toModel) :
    (∑ H₅ : FlagWithSize TetraFree emptyType 5,
        degGamma5 H₅ * ((subflagDensity H₅ (G₆.toFlag hG₆) : ℚ) : ℝ))
      = (((((sym3Reps 5).filter fun G =>
            decide (TetraFree.Mem G.toModel)).map
          fun G₅ => gamma5C G₅ * ((G₅.flagCountC G₆ : ℚ) / 6)).sum : ℚ) : ℝ) := by
  rw [sum_flag_eq_sum_sym3FlagReps TetraFree
    (fun M (hM : TetraFree.Mem M) => hM.1)
    (fun H₅ => degGamma5 H₅ * ((subflagDensity H₅ (G₆.toFlag hG₆) : ℚ) : ℝ)),
    sym3FlagReps, List.map_pmap]
  rw [pmap_sum_eq _
    (fun G₅ => ((gamma5C G₅ * ((G₅.flagCountC G₆ : ℚ) / 6) : ℚ) : ℝ)) ?_ _ _]
  · rw [cast_list_sum, List.map_map]
    rfl
  · intro G₅ hG₅
    rw [degGamma5_eq_gamma5C hG₅,
      Sym3Graph.subflagDensity_toFlag hG₅ hG₆,
      show Nat.choose 6 5 = 6 from rfl]
    push_cast
    ring

/-- **The abstract coefficient is the computable one**, on every literal
six-vertex host. -/
theorem stationarity_coeff_eq (G₆ : Sym3Graph 6)
    (hG₆ : TetraFree.Mem G₆.toModel) :
    ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
          (edgeGraph.toFlag edgeGraph_mem) (G₆.toFlag hG₆) : ℚ) : ℝ)
        - (∑ H₅ : FlagWithSize TetraFree emptyType 5,
            degGamma5 H₅ * ((subflagDensity H₅ (G₆.toFlag hG₆) : ℚ) : ℝ))
      = ((statCoeffC G₆ : ℚ) : ℝ) := by
  rw [statSum_eq G₆ hG₆,
    Sym3Graph.subflagPairDensity_toFlag edgeGraph_mem edgeGraph_mem hG₆,
    show pairChoose 6 3 3 = 20 from rfl]
  have h : statCoeffC G₆
      = (edgeGraph.flagPairCountC edgeGraph G₆ : ℚ) / 20
        - (((sym3Reps 5).filter fun G =>
              decide (TetraFree.Mem G.toModel)).map
            fun G₅ => gamma5C G₅ * ((G₅.flagCountC G₆ : ℚ) / 6)).sum := rfl
  rw [h]
  push_cast
  ring

/-! ## The per-class check and the identification -/

/-- **The certificate's stationarity count is 180 times the abstract
coefficient**, on every listed representative: one rational check per
class. The factor `3` between `statNum/60` and the coefficient is the
certificate's convention. -/
lemma statNum_check :
    (h6Reps.all fun h => decide ((statNum h : ℚ)
      = 180 * statCoeffC (graphOfMask 6 h))) = true := by
  native_decide

lemma statNum_eq_of_mem {h : ℕ} (hh : h ∈ h6Reps) :
    (statNum h : ℚ) = 180 * statCoeffC (graphOfMask 6 h) := by
  have := List.all_eq_true.mp statNum_check h hh
  simpa using this

/-- **The stationarity identification**: the certificate's level-6
stationarity element is three times the degree stationarity element. -/
theorem statElt6_eq : statElt6 = (3 : ℝ) • degreeStationarity := by
  have hstat : statElt6 = ∑ H : FlagWithSize TetraFree emptyType 6,
      ((statNumOf H / 60 : ℚ) : ℝ) •
        (⟦basisVector (⟨6, H⟩ : FinFlag TetraFree emptyType)⟧
          : FlagAlgebra TetraFree emptyType) := rfl
  rw [hstat, degreeStationarity_expand6, Finset.smul_sum]
  refine Finset.sum_congr rfl fun H _ => ?_
  rw [smul_smul]
  have hcoeff : ((subflagPairDensity (edgeGraph.toFlag edgeGraph_mem)
        (edgeGraph.toFlag edgeGraph_mem) H : ℚ) : ℝ)
      - ∑ H₅ : FlagWithSize TetraFree emptyType 5,
          degGamma5 H₅ * ((subflagDensity H₅ H : ℚ) : ℝ)
      = ((statCoeffC (graphOfMask 6 (repMask H)) : ℚ) : ℝ) := by
    conv_lhs => rw [← toFlag_repMask H (repMask_memT H)]
    exact stationarity_coeff_eq (graphOfMask 6 (repMask H)) (repMask_memT H)
  rw [hcoeff]
  have hnum : (statNumOf H / 60 : ℚ)
      = 3 * statCoeffC (graphOfMask 6 (repMask H)) := by
    have h1 : statNumOf H = statNum (repMask H) := rfl
    have h2 := statNum_eq_of_mem (repMask_mem H)
    rw [h1, h2]
    ring
  rw [hnum]
  push_cast
  ring_nf

end FlagAlgebras.Core.Tetrahedron.FullSevenLong
